[refactor] Extract external members from formal members
kaiyuanshe/kaiyuanshe.github.io pull request #101
Opened 2023-02-12 13:53 UTC by Five-great

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2023-02-13 07:24 UTC, TechQuery requested changes

2023-02-13 07:24 UTC, TechQuery commented on components/Group/Tree.tsx
> +import { EventHandler } from 'echarts-jsx/dist/utility';
```suggestion
import Router from 'next/router';
import { SVGCharts, Tooltip, TreeSeriesProps, TreeSeries } from 'echarts-jsx';
import { EventHandler } from 'echarts-jsx/dist/utility';

import { GroupCard } from './Card';
import groupStore from '../../models/Group';
import { i18n } from '../../models/Translation';
```

2023-02-13 07:24 UTC, TechQuery commented on components/Group/Tree.tsx
> +  jumpLink(e:any){
```suggestion
  jumpLink: EventHandler = event => {
```

2023-02-13 07:24 UTC, TechQuery commented on components/Group/Tree.tsx
> +      Router.push("/members#"+e.data.anchor, undefined, {scroll: false})
统一用 `location.pathname = '/route/path#fragment'` 的形式

2023-02-13 07:24 UTC, TechQuery commented on components/Group/Tree.tsx
> +         }
用 CSS：https://developer.mozilla.org/zh-CN/docs/Web/CSS/scroll-behavior

2023-02-13 07:24 UTC, TechQuery commented on components/Group/Tree.tsx
> +            onClick={this.jumpLink}
**事件回调**属性放最后

2023-02-13 07:24 UTC, TechQuery commented on components/Member/List.tsx
> +
确保本地 Git 能执行：
```shell
chmod +x .husky/pre-commit
chmod +x .husky/pre-push
```

2023-02-13 07:24 UTC, TechQuery commented on components/Member/Tabs.tsx
>  import { Member } from '../../models/Member';
```suggestion
import { Tabs, Tab } from 'react-bootstrap';

import { isServer } from '../../models/Base';
import { Member } from '../../models/Member';
```

2023-02-13 07:24 UTC, TechQuery commented on models/Member.ts
> +    }
```suggestion
  async getStatic(organization = '') {
    const list = await this.getAll({ organization });
```

2023-02-13 07:24 UTC, TechQuery commented on components/data.ts
> +      }
外部委员会用同一张数据表，以不同 `type` 分组，因为数据结构都是一样的；前端也放到同一个页面，布局和正式成员一样，因为数量比正式成员少多了。

2023-02-17 06:46 UTC, Five-great commented on components/Group/Tree.tsx
> +      Router.push("/members#"+e.data.anchor, undefined, {scroll: false})
哪我统一用这个 Router.push   我需要用这个跳

2023-02-17 07:11 UTC, Five-great commented on components/Group/Tree.tsx
> +         }
![image](https://user-images.githubusercontent.com/43601963/219574086-fb68ea24-e71b-42fa-8900-cf519c800d43.png)
知道这个 不适合 我需要有一定top偏移 以求更好效果

2023-02-17 07:15 UTC, Five-great commented on components/Member/List.tsx
> +
这 撒情况 不能运行么 这个

2023-02-17 07:21 UTC, Five-great commented on components/data.ts
> +      }
意思 在前端展示  合并到一起  所有外部委员   但是我感觉 外部委员感觉有点不好听 看换一个撒 高大上的不  看开会讨论下

2023-02-17 07:24 UTC, TechQuery commented on components/Member/List.tsx
> +
从实际情况看，你的 hook 就是没有运行，你重新执行一下命令

2023-02-17 07:26 UTC, TechQuery commented on components/data.ts
> +      }
不仅前端展示要放在一个页面，后端数据也要放在同一张表。

导航链接名字可以叫“专家委员会”，具体文案可以再调。

2023-02-18 08:33 UTC, Five-great commented on components/data.ts
> +      }
不是正式成员也有么外部委员么 还是要单独弄成两份 看可以 用飞书的CI 自动同步另一张表不

2023-02-18 08:34 UTC, Five-great commented on components/Member/List.tsx
> +
我是用的云ide 没用本地开发环境 之前本地开发环境 安装依赖 一些库可能把我电脑整崩

2023-02-26 11:38 UTC, TechQuery requested changes

2023-02-26 11:38 UTC, TechQuery commented on components/Group/Tree.tsx
> +            target: '/expertcommittee#顾问委员会',
```suggestion
            target: '/expert-committee#顾问委员会',
```

2023-02-26 11:38 UTC, TechQuery commented on components/Member/Static.tsx
> +        <MemberList list={otherMembersList}/>
从这里看来，代码格式化脚本执行有问题

2023-02-26 11:38 UTC, TechQuery commented on models/Expert.ts
> +const EXPERT_LIST = process.env.NEXT_PUBLIC_EXPERT_LIST! || `["顾问委员会","法律咨询委员会"]`;
1. 尽量不要手写 JSON 字符串，不太可靠
2. 这个配置感觉必要性不大，要展示的都在多维表格里面，比较确定；一定用过滤的话，就重定义接口 filter

2023-02-26 11:38 UTC, TechQuery commented on models/Member.ts
> +    } catch (_) {}
数据迁移过去了就不需要这个了

2023-02-26 11:38 UTC, TechQuery commented on pages/members/[type].tsx
> +});
服务端请求的逻辑里并没有用上路径上的 `[type]`，不太理解这里是怎么做区分的？

2023-02-26 11:47 UTC, Five-great commented on components/Group/Tree.tsx
> +            target: '/expertcommittee#顾问委员会',
这个是路径expertcommittee

2023-02-26 11:53 UTC, Five-great commented on models/Expert.ts
> +const EXPERT_LIST = process.env.NEXT_PUBLIC_EXPERT_LIST! || `["顾问委员会","法律咨询委员会"]`;
不是 因为 是新建的一张表  是从正式成员过滤了的拖过来的 有些人是正式成员且多种身份 比如 他是 顾问委员会","法律咨询委员会， 董事会 执行委员会  分类的时候  不处理 就会再专家委员会 显示 董事会 执行委员会 撒的  这里配置 我是防止以后 有其他外部委员 所以有一个配置 后面增加 就配置 ["顾问委员会","法律咨询委员会"，“xxx委员会”] ，就可以显示出来了 不需要再去 代码里面改 。 也可以不要 增加的可能不大 近期

2023-02-26 11:55 UTC, Five-great commented on models/Member.ts
> +    } catch (_) {}
因为现在还没迁移 所以保留  try 一下就是防止 以后迁移了 程序就报错 页面打不开

2023-02-26 11:57 UTC, Five-great commented on pages/members/[type].tsx
> +});
现在确实没type 了 可以不用这种模式 现在不是 外部委员单独一个页面 一张表 所以 新建了一个模型 （飞书的tableID 单独出来了）[type] 确实没用上了 现在

2023-02-26 12:00 UTC, Five-great commented on components/Member/Static.tsx
> +        <MemberList list={otherMembersList}/>
是格式化这么干的
![image](https://user-images.githubusercontent.com/43601963/221409137-b1a5b52b-3afd-4c69-b194-ac1c1af729a8.png)

2023-02-26 13:58 UTC, TechQuery commented on components/Group/Tree.tsx
> +            target: '/expertcommittee#顾问委员会',
我就是要你把路径改成我说的那样，否则太长了不清楚。

2023-02-26 14:00 UTC, TechQuery commented on components/Group/Tree.tsx
> +         }
CSS 现在有属性设**滚动偏移**

2023-02-26 14:03 UTC, TechQuery commented on components/Member/List.tsx
> +
云开发环境是 Linux，更需要你执行一下上面的命令来确保钩子能正常运行。

2023-02-26 14:04 UTC, TechQuery commented on components/data.ts
> +      }
正式成员也是外部委员的不太多，外部委员本来就没多少，手工复制粘贴一下也够用。

2023-02-26 14:05 UTC, TechQuery commented on components/Member/Static.tsx
> +        <MemberList list={otherMembersList}/>
本地的格式化插件有时会出现 bug，我们统一用项目里面安装的。

2023-02-26 14:07 UTC, TechQuery commented on models/Expert.ts
> +const EXPERT_LIST = process.env.NEXT_PUBLIC_EXPERT_LIST! || `["顾问委员会","法律咨询委员会"]`;
那就用简化一点的形式：`A委员会,B委员会`

2023-02-26 14:08 UTC, TechQuery commented on models/Member.ts
> +    } catch (_) {}
现在就迁移一下吧

2023-02-26 14:09 UTC, TechQuery commented on pages/members/[type].tsx
> +});
那就把文件名写明确吧

2023-02-27 04:58 UTC, Five-great commented on pages/members/[type].tsx
> +});
明确了

2023-02-27 04:58 UTC, Five-great commented on models/Member.ts
> +    } catch (_) {}
去掉了

2023-03-05 11:13 UTC, TechQuery requested changes

2023-03-05 11:13 UTC, TechQuery commented on pages/members/expert.tsx
> +    AnchorJump(query.anchor as string);
切忌在 render 函数中直接写任何**非数据逻辑**！因为它会频繁、不定时地执行，任何副作用代码都要写在 `useEffect()` 或者 `componentDidMount()` 回调中。

所以还是建议用包装组件的方式：
```tsx
export const Anchor: FC<{ id: string, offsetTop: number, offsetLeft: number }> = ({ id, offsetTop, offsetLeft, children }) =>
    <div className="position-relative">
        <span
          id={id}
          className="position-absolute"
          style={{ top: offsetTop, left: offsetLeft }}
        />
        {children}
    </div>;
```

2023-03-12 04:01 UTC, TechQuery requested changes

2023-03-12 04:01 UTC, TechQuery commented on components/Member/Title.tsx
> +    )}
```suggestion
    className={`position-relative border-bottom border-2 border-info lh-lg mb-4 ${styles.memberTitle}`}
```

2023-03-12 04:18 UTC, Five-great commented on pages/members/index.tsx
> +      scrollTo('#' + query!.anchor);
这个不合适  根据习惯 还是从上（头）开始看 所以没用屏幕中央

2023-03-12 04:18 UTC, Five-great commented on pages/members/index.tsx
> +      scrollTo('#' + query!.anchor);
我加了样式 不会遮挡 效果一样

2023-03-12 05:19 UTC, Five-great commented on pages/members/index.tsx
> +      scrollTo('#' + query!.anchor);
这是居中效果  在内容较多时只展示一小部分 想要查看的部分
![image](https://user-images.githubusercontent.com/43601963/224525752-29aacdc6-e2c3-4e84-a1b6-7010d18dc7c6.png)
这是顶部效果  在内容较多时只展示一较多部分 想要查看的部分
![image](https://user-images.githubusercontent.com/43601963/224525880-ca50abff-e86e-498b-9982-abe235641958.png)

2023-03-12 12:24 UTC, TechQuery approved these changes

2023-03-12 15:55 UTC, TechQuery approved these changes

2023-03-12 15:56 UTC, merged