refactor: Rewrite license tool
kaiyuanshe/kaiyuanshe.github.io pull request #107
Opened 2023-05-17 13:49 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #69

2023-05-18 08:41 UTC, TechQuery requested changes

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +  // console.log(list); // filtered licenses
```suggestion
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +    }
```suggestion
    if (stepIndex === chooseSteps.length) setDisableDropdown(true);
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +    console.log('list', lists);
```suggestion
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +              <Dropdown.Item eventKey={info.value}>{info.text}</Dropdown.Item>
```suggestion
            disabled={disableDropdown}
            title={choose || '请选择'}
          >
            {choose || '请选择'}
          </Dropdown.Toggle>
          <Dropdown.Menu>
            {optionValue[chooseSteps[keyIndex]].map(({ value, text }) => (
              <Dropdown.Item key={value} eventKey={value}>{text}</Dropdown.Item>
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +      </div> */}
这是怎么回事？

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +      <div>
```suggestion
      <div className="mt-3">
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +              <Accordion.Body>{renderInfo(list.license)}</Accordion.Body>
```suggestion
          {list.map(({ license, score }, index) => (
            <Accordion.Item key={license.name} eventKey={(index + 1) + ''}>
              <Accordion.Header>
                {license.name} 评分: {score * 10}
              </Accordion.Header>
              <Accordion.Body>{renderInfo(license)}</Accordion.Body>
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +  let choose: string | null = null;
```suggestion
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +  }
```suggestion
  const judge = (attitude: FeatureAttitude) =>
    ({
      [FeatureAttitude.Positive]: 'Yes',
      [FeatureAttitude.Negative]: 'No'
    })[attitude] || '不明确';
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +function renderInfo(info: License) {
```suggestion
function renderInfo({ link, feature }: License) {
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +    </div>
```suggestion
  <>
    <ul>
      <li>流行程度：{judge(feature.popularity)}</li>
      <li>复用条件：{judge(feature.reuseCondition)}</li>
      <li>传染强度：{judge(feature.infectionIntensity)}</li>
      <li>传染范围：{
          feature.infectionRange
            ? feature.infectionRange in key
              ? key[feature.infectionRange]
              : '不明确'
            : '不明确'
      }</li>
      <li>法律管辖：{judge(feature.jurisdiction)}</li>
      <li>专利声明：{judge(feature.patentStatement)}</li>
      <li>专利报复：{judge(feature.patentRetaliation)}</li>
      <li>增强署名：{judge(feature.enhancedAttribution)}</li>
      <li>隐私漏洞：{judge(feature.privacyLoophole)}</li>
      <li>营销背书：{judge(feature.marketingEndorsement)}</li>
    </ul>
    <Button size="sm" target="_blank" href={link}>协议详情</Button>
  </>
```

2023-05-18 08:41 UTC, TechQuery commented on pages/license-tool.tsx
> +  const key = {
```suggestion
  const InfectionRangeKey = {
```

2023-05-19 03:28 UTC, luojiyin1987 commented on components/License/helper.ts
> +  ],
通过 license-filter 的原始数据迭代生成数据，而不是手工维护？

2023-05-19 04:01 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +    console.log(chooseSteps[keyIndex]);
`const choice = +value;`   vlaue 的值可能为 null

2023-05-19 04:10 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +      </div> */}
这是以前验证计算结果的

2023-05-19 04:20 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +  let choose: string | null = null;
？

2023-05-19 06:32 UTC, TechQuery commented on components/License/helper.ts
> +  ],
不需要，就是把这块数据用 `.map()` + `Object.fromEntries()` 生成出来，因为每一项的内容都是一样的。

2023-05-19 06:33 UTC, TechQuery commented on components/License/helper.ts
> +  ],
不需要，就是把这块数据用 `.map()` + `Object.fromEntries()` 生成出来，因为每一项的内容都是一样的。

2023-05-19 06:34 UTC, TechQuery commented on pages/license-tool.tsx
> +    console.log(chooseSteps[keyIndex]);
> `const choice = +value;`   vlaue 的值可能为 null   

`+null === 0`

2023-05-19 06:35 UTC, TechQuery commented on pages/license-tool.tsx
> +    console.log(chooseSteps[keyIndex]);
> `const choice = +value;`   vlaue 的值可能为 null   

`+null === 0`

2023-05-19 06:35 UTC, TechQuery commented on pages/license-tool.tsx
> +      </div> */}
> 这是以前验证计算结果的

没用就删

2023-05-19 06:39 UTC, TechQuery commented on pages/license-tool.tsx
> +  let choose: string | null = null;
你这个变量没有真正用到，因为你没有操作它。

建议你把下拉菜单改成平铺的三个单选框，这样你就不需要处理下拉框按钮文字的变化，用户也不需要点击两次。

2023-05-19 08:27 UTC, TechQuery requested changes

2023-05-19 08:27 UTC, TechQuery commented on components/License/helper.ts
> +};
`Record`

2023-05-19 08:27 UTC, TechQuery commented on components/License/helper.ts
> +export const licenseKeyInfo = {};
这是干嘛的？

2023-05-19 08:27 UTC, TechQuery commented on pages/license-tool.tsx
> +    setFilterOption({ ...newObject });
```suggestion
    setFilterOption(newObject);
```

2023-05-19 08:27 UTC, TechQuery commented on pages/license-tool.tsx
> +            // eslint-disable-next-line react/jsx-key
```suggestion
```

2023-05-19 08:49 UTC, luojiyin1987 commented on components/License/helper.ts
> +export const licenseKeyInfo = {};
我也忘了 。

2023-05-19 09:07 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +    console.log(chooseSteps[keyIndex]);
`+null === 0`   是什么意思

2023-05-19 09:32 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +    console.log(chooseSteps[keyIndex]);
我改成   `const choice =  value? +value: 0 ; ` 了

2023-05-19 09:46 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +  }
我写成了
```typescript
const judge = (attitude: FeatureAttitude) =>
    ({
      [FeatureAttitude.Positive]: 'Yes',
      [FeatureAttitude.Negative]: 'No',
      [FeatureAttitude.Undefined]: '不明确',
    }[attitude] || '不明确');
```

2023-05-19 09:49 UTC, luojiyin1987 commented
TODO
1  要把变量 `optionValue`  和 `licenseTips`   跟国际化 结合
2  优化下拉条件选择过程， 把点击两次 变成 点击一次

2023-05-20 06:12 UTC, TechQuery requested changes

2023-05-20 06:12 UTC, TechQuery commented on pages/license-tool.tsx
> +  ];
静态数据提到组件外面去

2023-05-20 06:12 UTC, TechQuery commented on pages/license-tool.tsx
> +              onClick={e => handleChoose(e.currentTarget.value)}
```suggestion
              onClick={({ currentTarget: { value } }) => handleChoose(value)}
```

2023-05-20 15:43 UTC, TechQuery commented on pages/license-tool.tsx
> +  };
```suggestion
  const judgeInfectionRange = (infectionRange?: InfectionRange) =>
    infectionRange != null ? {
      [InfectionRange.Library]: 'Library',
      [InfectionRange.File]: 'File',
      [InfectionRange.Module]: 'Module',
    }[infectionRange] : '不明确';
```

2023-05-21 10:41 UTC, TechQuery requested changes

2023-05-21 10:41 UTC, TechQuery commented on pages/license-tool.tsx
> +      </div>
```suggestion
        {licenseTips[chooseSteps[keyIndex]].map(({ text }) => (
          <p key={text}>{text}</p>
        ))}

        <ProgressBar
          className="mb-3"
          variant="info"
          now={(keyIndex + 1) * now}
          label={`第${keyIndex + 1}步`}
        />

        <ButtonGroup className="mb-3">
          {optionValue[chooseSteps[keyIndex]].map(({ value, text }) => (
            <ToggleButton
              key={value}
              value={value}
              id={`tb-${value}`}
              disabled={disableChoose}
              onClick={({ currentTarget: { value } }) => handleChoose(value)}
            >
              {text}
            </ToggleButton>
          ))}
        </ButtonGroup>

        <Accordion defaultActiveKey="0">
          {lists.map(({ license, score }, index) => (
            <Accordion.Item key={license.name} eventKey={index + 1 + ''}>
              <Accordion.Header>
                {license.name} 评分: {score * 10}
              </Accordion.Header>
              <Accordion.Body>{renderInfo(license)}</Accordion.Body>
            </Accordion.Item>
          ))}
        </Accordion>
```

2023-05-21 13:24 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +      </div> */}
已经删除

2023-05-22 03:27 UTC, luojiyin1987 commented
license-tool 页面的国际化还没做好，  繁体中文和英文内容还需要别人看一看。

2023-05-22 05:34 UTC, TechQuery requested changes

2023-05-22 05:34 UTC, TechQuery commented on components/License/helper.ts
> +    },
```suggestion
    { text: t('tip_popularity_0') },
    { text: t('tip_popularity_1') },
  ],
  reuseCondition: [{ text: t('tip_reuse_condition') }],
  infectionIntensity: [{ text: t('tip_infection_intensity') }],
  jurisdiction: [{ text: t('tip_jurisdiction') }],
  patentStatement: [{ text: t('tip_patent_statement') }],
  patentRetaliation: [{ text: t('tip_patent_retaliation') }],
  enhancedAttribution: [{ text: t('tip_enhanced_attribution') }],
  privacyLoophole: [{ text: t('tip_privacy_loophole') }],
  marketingEndorsement: [{ text: t('tip_marketing_endorsement') }],
  infectionRange: [
    { text: t('tip_infection_range') },
```

2023-05-22 05:34 UTC, TechQuery commented on pages/license-tool.tsx
> +        协议详情
这些文字也要放到国际化文件里

2023-05-22 05:39 UTC, TechQuery requested changes

2023-05-22 05:39 UTC, TechQuery commented on pages/license-tool.tsx
> +const LicenseTool: NextPage = () => {
国际化依赖 MobX，组件需要用 `observer()` 包裹一下。

2023-05-22 05:39 UTC, TechQuery commented on components/License/helper.ts
> +};
```suggestion
const licenseTips: () => LicenseTips = () => ({
  popularity: [
    {
      text: t('tip_popularity_0'),
    },
    {
      text: t('tip_popularity_1'),
    },
  ],
  reuseCondition: [{ text: t('tip_reuse_condition') }],
  infectionIntensity: [{ text: t('tip_infection_intensity') }],
  jurisdiction: [{ text: t('tip_jurisdiction') }],
  patentStatement: [{ text: t('tip_patent_statement') }],
  patentRetaliation: [{ text: t('tip_patent_retaliation') }],
  enhancedAttribution: [{ text: t('tip_enhanced_attribution') }],
  privacyLoophole: [{ text: t('tip_privacy_loophole') }],
  marketingEndorsement: [{ text: t('tip_marketing_endorsement') }],
  infectionRange: [
    {
      text: t('tip_infection_range'),
    },
  ],
});
```
静态数据需要用箭头函数包裹一下，以便 MobX 更新时取到最新的国际化文本。

2023-05-22 11:11 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +const LicenseTool: NextPage = () => {
还不太理解， 在看文档 代码中

2023-05-22 11:11 UTC, luojiyin1987 commented on components/License/helper.ts
> +};
在导入使用时， 不是要实例化？

2023-05-23 08:12 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +const LicenseTool: NextPage = () => {
是不是要写成这样  ???
```typescript
const PageHead: FC<PageHeadProps> = observer(
  ({ title, description = Summary, children }) => (
    <Head>
      <title>
        {title}
        {title && ' - '}
        {t('KaiYuanShe')}
      </title>

      {description && <meta name="description" content={description} />}

      {children}
    </Head>
  ),
);
```

2023-05-23 09:49 UTC, luojiyin1987 commented on components/License/helper.ts
> +};
是不是 我要把 生成页面的函数提取到  components/License/helper.ts ？

2023-05-23 10:05 UTC, TechQuery commented on components/License/helper.ts
> +};
> 是不是 我要把 生成页面的函数提取到  components/License/helper.ts ？ 

和页面啥关系？你按我建议的写就没错。

2023-05-23 12:24 UTC, luojiyin1987 commented on components/License/helper.ts
> +};
```typescript
{licenseTips[chooseSteps[keyIndex]].map(({ text }) => (
        <p key={text}>{text}</p>
      ))}
```报
在类型 "() => LicenseTips" 上找不到具有类型为 "string" 的参数的索引签名。

2023-05-23 14:34 UTC, TechQuery requested changes

2023-05-23 14:34 UTC, TechQuery commented on components/License/helper.ts
> +    (optionValue: OptionValue, option) => {
```suggestion
const optionValue = () => {
  const optionValue = options.reduce(
    (optionValue, option) => {
```
数据起始位置标清类型，后面都能推导（见下一条）

2023-05-23 14:34 UTC, TechQuery commented on components/License/helper.ts
> +    {},
```suggestion
    {} as OptionValue,
```

2023-05-23 14:34 UTC, TechQuery commented on components/License/helper.ts
> +console.log('licenseTips helper', licenseTips);
```suggestion
```

2023-05-23 14:34 UTC, TechQuery commented on components/License/helper.ts
> +  // 'infectionRange',
```suggestion
```

2023-05-23 14:34 UTC, TechQuery commented on pages/license-tool.tsx
> +console.log('licenseTips', licenseTips);
```suggestion
```

2023-05-23 14:43 UTC, luojiyin1987 commented on components/License/helper.ts
> +};
> > 是不是 我要把 生成页面的函数提取到  components/License/helper.ts ？
> 
> 和页面啥关系？你按我建议的写就没错。

返回一个箭头函数,产生闭包效果 ？

2023-05-23 16:14 UTC, TechQuery commented on components/License/helper.ts
> +};
> 返回一个箭头函数,产生闭包效果 ？ 

不是返回一个箭头函数，是导出一个箭头函数。

也不是利用什么闭包特性。仅仅是因为模块中的静态数据只在模块解析时生成一遍，要想在组件重绘时更新数据，就不能是纯静态的。所以只有函数才可以在每次组件渲染时重新执行代码，来获取最新的值。

2023-05-23 16:15 UTC, TechQuery requested changes

2023-05-23 16:15 UTC, TechQuery commented on components/License/helper.ts
> +const { t } = i18n;
```suggestion
import { FeatureAttitude, InfectionRange } from 'license-filter';

import { i18n } from '../../models/Translation';

const { t } = i18n;
```

2023-05-23 16:16 UTC, TechQuery approved these changes

2023-05-24 06:41 UTC, TechQuery requested changes

2023-05-24 06:41 UTC, TechQuery commented on pages/license-tool.tsx
> +        label={t('step') + (keyIndex + 1) + t('step_unit')}
改为函数形式，参考：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/ca1c00abbd8a80bc5651928b31a6ebb900e46a70/translation/zh-CN.ts#L67-L68

2023-05-24 07:32 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +        label={t('step') + (keyIndex + 1) + t('step_unit')}
```typescript
step: ({ keyIndex }: { keyIndex: number }) => `step ${keyIndex + 1}`
```
有点担心， 我写法隐藏得太深。

2023-05-24 10:27 UTC, TechQuery approved these changes

2023-05-24 12:26 UTC, PapayaHUANG requested changes
英译中修改意见，有问题随时联系我：）

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  tip_patent_retaliation: '您是否想使用包含专利报复条款的许可协议',
`patent retaliation clause`的简中翻译是`专利反击条款`
`专利报复条款`是繁体中文翻译

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  tip_enhanced_attribution: '您是否想使用指定“增强型归属”的许可协议',
`enhanced attribution`是`增强溯源`

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  tip_marketing_endorsement: '您是否想允许推广的许可协议',
`promotional license`是`促销授权`
https://wiki.mbalib.com/wiki/%E5%93%81%E7%89%8C%E6%8E%88%E6%9D%83

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +    '该工具旨在帮助用户理解他们自己对于自由和开源软件许可协议的偏好。用户必须自己阅读这些许可协议。在将许可协议适用于您的项目之前，阅读并完全理解您选择的许可协议是非常重要的。支撑该工具运行的许可类型分类，会不可避免地有些缩减。因此，不能也切不可将该工具的输出信息视为法律意见。',
本工具旨在帮助用户了解自己对开源软件许可协议的偏好。用户必须自行阅读这些许可协议。在应用到项目之前，用户阅读并完全理解许可协议非常重要。本工具借用的许可分类方式不能保证永远适用，因此，不可将本工具输出的信息作为法律依据。

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  option_undefined: '不明确',
我不知道这个单词的上下文
但是就单词本身来看`not required`是`不要求`
可以根据上下文来决定是否采纳我的意见

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  feature_patent_retaliation: '专利报复',
同上

2023-05-24 12:26 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  feature_enhanced_attribution: '增强署名',
同上

2023-05-24 13:48 UTC, luojiyin1987 commented on translation/zh-CN.ts
> +  tip_patent_retaliation: '您是否想使用包含专利报复条款的许可协议',
这个我保留意见，报复 比 反击 更好理解
```suggestion
  tip_patent_retaliation: '您是否想使用包含专利报复条款的许可协议',
```

2023-05-24 13:53 UTC, luojiyin1987 commented on translation/zh-CN.ts
> +  tip_enhanced_attribution: '您是否想使用指定“增强型归属”的许可协议',
我建议翻译成  增强型软件归属标注，比标准的归属标注要求更加严格和全面地标注软件的创作来源和归属信息。

2023-05-24 13:56 UTC, luojiyin1987 commented on translation/zh-CN.ts
> +  tip_marketing_endorsement: '您是否想允许推广的许可协议',
我保留意见。 “marketing endorsement” 指允许商业公司为市场营销目的而推广或者认可该开源软件。  促销授权 有清仓大减价的感觉。

2023-05-24 14:00 UTC, luojiyin1987 commented on translation/zh-CN.ts
> +  feature_patent_retaliation: '专利报复',
哪个同上？

2023-05-24 14:01 UTC, luojiyin1987 commented on translation/zh-CN.ts
> +  feature_enhanced_attribution: '增强署名',
我保留意见，我建议改成   `增强型软件归属标注`,  是否更容易理解？

2023-05-24 14:10 UTC, TechQuery requested changes

2023-05-24 14:40 UTC, PapayaHUANG commented on translation/zh-CN.ts
> +  feature_enhanced_attribution: '增强署名',
可，你考虑下是“归属增强”还是“增强归宿”哈

2023-05-24 14:47 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +          [InfectionRange.Module]: 'Module',
我的想法是直接用英文好理解

2023-05-24 15:20 UTC, TechQuery approved these changes

2023-05-24 15:29 UTC, PapayaHUANG approved these changes

2023-05-25 09:45 UTC, TechQuery commented on pages/license-tool.tsx
> +        label={t('step') + (keyIndex + 1) + t('step_unit')}
> ```typescript
> step: ({ keyIndex }: { keyIndex: number }) => `step ${keyIndex + 1}`
> ```
> 有点担心， 我写法隐藏得太深。

没理解你的担心在哪？

2023-05-25 09:46 UTC, TechQuery approved these changes

2023-05-25 09:47 UTC, merged

2023-05-25 12:39 UTC, luojiyin1987 commented on pages/license-tool.tsx
> +        label={t('step') + (keyIndex + 1) + t('step_unit')}
`{t('step', { keyIndex })}`   后面隐藏的 `+1`  操作， 无法通过  IDE 跳转查到。