Feat invitation card
kaiyuanshe/kaiyuanshe.github.io pull request #110
Opened 2023-05-30 08:21 UTC by luojiyin1987

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #92

2023-06-26 15:19 UTC, wangrunlin requested changes

2023-06-26 15:19 UTC, wangrunlin commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        <h3>👨‍🎓 {(agenda.mentors as string[]).join(' ')}</h3>
```suggestion
        <h2>
          🕒 {new Date(+startTime!).toLocaleString()} ~{' '}
          {new Date(+endTime!).toLocaleString()}
        </h2>
        <h3>{title}</h3>
        <p>show</p>
        <h3>👨‍🎓 {(mentors as string[]).join(' ')}</h3>
```
参数在上方解构

2023-06-26 15:19 UTC, wangrunlin commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  return (
```suggestion
  };

  return (
```

2023-06-26 15:19 UTC, wangrunlin commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        .catch(error => console.log('Error sharing', error));
改造为 `async` `await` 语法

2023-06-26 15:19 UTC, wangrunlin commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +    console.log('shareURL');
调试日志可删除。

2023-06-28 14:45 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +> = async context => {
在这里套一层 `withRoute()`，即可在组件取到 `props.route.resolvedUrl`。

2023-06-29 13:51 UTC, TechQuery requested changes

2023-06-29 13:51 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  }`;
先导出一个常量：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/1563b159ce602ec9576b186d5ab5a49ade789762/models/Base.ts#L8

再改为：
```suggestion
> = async ({ resolvedUrl, params, }) => {
  const activityStore = new ActivityModel(),
      { id, agendaId } = params!;
  const activity = await activityStore.getOne(id + '');
  const agenda = await activityStore.currentAgenda!.getOne(agendaId + '');
  const currentUrl = API_HOST + resolvedUrl;
```

2023-06-29 13:51 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  { currentUrl: string }
这个字段放到第一个类型参数里面

2023-06-29 13:51 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
>      },
```suggestion
    props: { activity, agenda, currentUrl },
```

2023-06-29 13:51 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
>      }
```ts
      try {
        await navigator.share?.({
          title: 'web.dev',
          text: 'Check out web.dev.',
          url: 'https://web.dev/',
        });
      } catch (error) {
        console.log('share error', error);
      }
```

2023-06-29 13:51 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        <h3>👨‍🎓 {(mentors as string[]).join(' ')}</h3>
这些信息不是“标题”，请用 `<ul />`。

2023-06-29 14:54 UTC, luojiyin1987 commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  { currentUrl: string }
```ts
 { activity: Activity; agenda: Agenda },
  { id: string; agendaId: string },
  { currentUrl: string }
```
不是这样吗？

2023-06-30 16:16 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  { currentUrl: string }
```ts
  { activity: Activity; agenda: Agenda, currentUrl: string },
```

2023-06-30 16:28 UTC, TechQuery requested changes

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +import { QRCodeSVG } from 'qrcode.react';
```suggestion
import Head from 'next/head';
import { FC } from 'react';
import { QRCodeSVG } from 'qrcode.react';
```

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +import { Activity, ActivityModel } from '../../../../../models/Activity';
```suggestion
import { DefaultImage } from '../../../../api/lark/file/[id]';
import { Activity, ActivityModel } from '../../../../../models/Activity';
```

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  : globalThis.location.origin;
那边导出、这边导入，不是复制粘贴……

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +      currentUrl,
```suggestion
  const { id, agendaId } = params!;

  const activity = await activityStore.getOne(id + ''),
    agenda = await activityStore.currentAgenda!.getOne(agendaId + '');

  return {
    props: {
      activity,
      agenda,
      currentUrl: API_Host + resolvedUrl,
```

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +      </Head>
全局已有，无需再设。

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        </ul>
认真看文档：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/ul

2023-06-30 16:28 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +    navigator.canShare({
```suggestion
  if (
    navigator.canShare?.({
```
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Optional_chaining#%E5%8F%AF%E9%80%89%E9%93%BE%E4%B8%8E%E5%87%BD%E6%95%B0%E8%B0%83%E7%94%A8

2023-07-01 15:31 UTC, luojiyin1987 commented on pages/activity/[id]/index.tsx
> +    navigator.canShare({
```ts
const shareInvitation = async () => {
  try {
    await navigator.share?.({
      title: 'web.dev',
      text: 'Check out web.dev.',
      url: 'https://web.dev/',
    });
    console.log('share success');
  } catch (error) {
    console.log('share error', error);
  }
};
```
我改成这样

2023-07-02 13:05 UTC, TechQuery requested changes

2023-07-02 13:05 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> -  { id: string; agendaId: string },
这个不要删

2023-07-02 13:05 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
>      <>
```suggestion
```

2023-07-02 13:56 UTC, TechQuery requested changes

2023-07-02 13:56 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  { currentUrl: string }
```suggestion
  { activity: Activity; agenda: Agenda, currentUrl: string },
  { id: string; agendaId: string },
```

2023-07-02 13:56 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +      <ul style={{ listStyle: 'none' }}>
```suggestion
      <ul className="list-unstyled">
```
https://getbootstrap.com/docs/5.3/content/typography/#unstyled

2023-07-03 14:10 UTC, TechQuery requested changes

2023-07-03 14:10 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +  const [imageDataURL, setImageDataURL] = useState<string | null>(null);
```suggestion
  const elementRef = useRef<HTMLDivElement>(null);
  const [imageDataURL, setImageDataURL] = useState('');
```

2023-07-03 14:10 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +    html2canvas(element!).then(canvas => {
改成 `await`

2023-07-03 14:10 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        </a>
国内一些移动应用内置浏览器阉割了这个功能

2023-07-03 14:30 UTC, luojiyin1987 commented
目前这种图片生成方式，  可以能出现短暂白屏， 页面生成速度还是比较慢。  @TechQuery

2023-07-03 14:32 UTC, TechQuery requested changes

2023-07-03 14:32 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        <div style={{ display: 'block' }}>
它本来就是 block，无需更改。

2023-07-03 14:32 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +      )}
```suggestion
      {!imageDataURL ? (
        <ul style={{ listStyle: 'none' }}>
          <li>{name}</li>
          <li>{city}</li>
          <li>{location}</li>
          <li>
            🕒 {new Date(+startTime!).toLocaleString()} ~{' '}
            {new Date(+endTime!).toLocaleString()}
          </li>
          <li>{title}</li>
          <li>👨‍🎓 {(mentors as string[]).join(' ')}</li>
          <li>
            <QRCodeSVG value={currentUrl} />
          </li>
        </ul>
      ) : (
          <Image fluid src={imageDataURL} alt="Generated" />
      )}
```

2023-07-04 06:29 UTC, TechQuery commented
> 目前这种图片生成方式，  可以能出现短暂白屏， 页面生成速度还是比较慢。  @TechQuery 

什么时候白屏？慢可以加一个 [`<Loading />`](https://idea-react.vercel.app/?path=/docs/idea-react-loading--docs)

2023-07-04 07:25 UTC, luojiyin1987 commented
> > 目前这种图片生成方式，  可以能出现短暂白屏， 页面生成速度还是比较慢。  @TechQuery
> 
> 什么时候白屏？慢可以加一个 [`<Loading />`](https://idea-react.vercel.app/?path=/docs/idea-react-loading--docs)

客户端渲染成后页面，再生成图片的时候会闪一下

2023-07-04 08:31 UTC, TechQuery commented
> 客户端渲染成后页面，再生成图片的时候会闪一下

那是因为新生成的图片加载有个过程，所以这就是为什么我给你参考的代码当中，是用 `position: absolute` 覆盖在原有结构上层，而不是简单地销毁之前的结构。

2023-07-04 14:26 UTC, luojiyin1987 commented
> > 客户端渲染成后页面，再生成图片的时候会闪一下
> 
> 那是因为新生成的图片加载有个过程，所以这就是为什么我给你参考的代码当中，是用 `position: absolute` 覆盖在原有结构上层，而不是简单地销毁之前的结构。

做了最简单的实验

2023-07-04 15:03 UTC, luojiyin1987 commented
有必要对 生成的图片进行缓存？ @TechQuery

2023-07-04 16:49 UTC, TechQuery commented
> 有必要对 生成的图片进行缓存？ @TechQuery 

没必要

2023-07-04 16:52 UTC, TechQuery requested changes

2023-07-04 16:52 UTC, TechQuery commented on styles/invitation.module.less
> +  position: 'relative';
```suggestion
  position: relative;
```

2023-07-04 16:52 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +            style={{ position: 'absolute', top: 80, left: 0, zIndex: 1 }}
自定义样式写到 LESS 文件中

2023-07-04 16:52 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +          <ul className="list-unstyled ">
```suggestion
      <Container className={styles.invitationBG} ref={elementRef}>
      {!imageDataURL && <Loading />}

        {!imageDataURL ? (
          <ul className="list-unstyled">
```

2023-07-05 01:53 UTC, luojiyin1987 commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +            style={{ position: 'absolute', top: 80, left: 0, zIndex: 1 }}
我试过， 不生效。

2023-07-05 01:54 UTC, luojiyin1987 commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +            style={{ position: 'absolute', top: 80, left: 0, zIndex: 1 }}
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/ba4960a7-c1ab-40e8-ad82-8a7d5b8b1059)

2023-07-05 02:11 UTC, luojiyin1987 commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +            style={{ position: 'absolute', top: 80, left: 0, zIndex: 1 }}
解决了， 改成了 
```less
top:10px 
```
加上单位就行了

2023-07-07 14:29 UTC, TechQuery requested changes

2023-07-07 14:29 UTC, TechQuery commented on models/Base.ts
> +    ? SelfHost
还原，本地开发直接手动注入 `VERCEL_URL`。

2023-07-07 14:29 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +      setImageDataURL(image as string);
```suggestion
      const image = await new Promise<string>(resolve =>
        canvas.toBlob(blob => resolve(URL.createObjectURL(blob)), 'image/jpeg', 0.92)
      );
      setImageDataURL(image);
```
https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLCanvasElement/toBlob

2023-07-07 14:29 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                      >
直接链接到分享页面，无需再写分享逻辑。

2023-07-07 15:42 UTC, TechQuery requested changes

2023-07-07 15:42 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +        blob => resolve(URL.createObjectURL(blob as Blob)),
```suggestion
    const image = await new Promise<string>((resolve, reject) =>
      canvas.toBlob(
        blob => blob ? resolve(URL.createObjectURL(blob)) : reject(),
```

2023-07-07 15:42 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/invitation.tsx
> +            <Image src={imageDataURL} alt="shareQRcode" fluid />
```suggestion
            <Image fluid src={imageDataURL} alt="shareQRcode" />
```

2023-07-07 15:42 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                        href={`./${activity.id}/agenda/${agenda.id}/invitation`}
```suggestion
                        href={`/activity/${activity.id}/agenda/${agenda.id}/invitation`}
```

2023-07-07 16:46 UTC, TechQuery approved these changes

2023-07-08 01:14 UTC, closed without merging