[feat] add forum model and staff component for activity page
kaiyuanshe/kaiyuanshe.github.io pull request #126
Opened 2023-07-10 08:03 UTC by PapayaHUANG

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #114 
 
我看到这个示例了https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/11caced6bb23286b04203118edefe995743af299/pages/activity/%5Bid%5D/agenda/%5BagendaId%5D/index.tsx#L79-L86

但是我把图片的拆分放到`<Staff />`组件内了。

why？
因为我还是沿用了昨天例会说的：在处理两张表的数据采取的策略是把数组和对象基于**论坛名**合并了。

why？
因为我又查看了 2011 年 Coscon 的数据，发现取出来的`forum`数据和 `agenda`不是完全对应的，会出现`forum`中`name`字段数量多过 `agenda`的`key`（也就是`agenda`里对应每一个**论坛名**）的情况。

这样做确实就会类型写得很恶心，所以我用了好几个 `any`，啊苍天！！！！

恳请大佬指正～

2023-07-10 12:29 UTC, TechQuery requested changes
合并主分支后，在项目根目录执行命令：
```shell
chmod +x .husky/pre-commit
chmod +x .husky/pre-push
```

2023-07-10 12:29 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +              } = agendas;
数组不要附加命名索引

2023-07-10 15:44 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                    name === forum && (
论坛迭代放到外面、议程放到里面，否则会多很多次迭代。

2023-07-10 15:46 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                        id="name"
```suggestion
```
`id` 在一个网页内唯一

2023-07-10 15:49 UTC, TechQuery commented on pages/activity/index.tsx
>    return (
省略 `{ return }`

2023-07-10 15:50 UTC, TechQuery commented on pages/index.tsx
> +          <Image fluid src="/image/Heart_of_Community.png" alt={'Head Image'} />
```suggestion
          <Image fluid src="/image/Heart_of_Community.png" alt="Head Image" />
```

2023-07-10 15:54 UTC, TechQuery commented on pnpm-lock.yaml
> +lockfileVersion: '6.0'
本地执行：

```shell
npm i pnpm@latest -g
pnpm i
```
就不会有此差异了。

2023-07-10 15:59 UTC, TechQuery commented on components/Activity/Agenda/People.tsx
> +          <li>{summaries && summaries[index]}</li>
还原，让外面来检查存在性。

2023-07-11 03:41 UTC, PapayaHUANG commented on models/Activity.ts
> +import { Forum,ForumModel } from './Forum';
我运行了：
`chmod +x .husky/pre-commit`
`chmod +x .husky/pre-push`
🤔️

2023-07-11 03:50 UTC, PapayaHUANG commented on components/Activity/Agenda/People.tsx
> +          <li>{summaries && summaries[index]}</li>
外面如何检查🤔️
我只想到 `name` 可以放在父组件用 `&&`
那其他的如何处理？

2023-07-11 07:52 UTC, TechQuery requested changes

2023-07-11 07:52 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                    <h6>{t('volunteer')}</h6>
```suggestion
                    <h3 className="h6">{t('producer')}</h3>
                    <AgendaPeople
                      names={producers as string[]}
                      avatars={(producerAvatars as TableCellValue[])?.map(
                        file => blobURLOf([file] as TableCellValue),
                      )}
                      positions={producerPositions as string[]}
                      summaries={[]}
                    />
                  </div>
                  <div className="d-flex align-items-center px-5">
                    <h3 className="h6">{t('volunteer')}</h3>
```
语义是语义，样式是样式。

2023-07-11 07:52 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +                )}
```suggestion
                <Row
                        as="ol"
                        className="list-unstyled g-4"
                        key={forum}
                        xs={1}
                        sm={2}
                        md={3}
                      >
                        {agendaGroup[forum].map(agenda => (
                          <Col as="li" key={agenda.id + ''}>
                            <AgendaCard
                              activityId={activity.id + ''}
                              location={activity.location + ''}
                              {...agenda}
                            />
                          </Col>
                        ))}
                      </Row>
```

2023-07-11 08:29 UTC, PapayaHUANG commented on pnpm-lock.yaml
> +lockfileVersion: '6.0'
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/0dcfea02-5265-4734-9326-8727c50aaf01)
改了呀

2023-07-11 09:00 UTC, TechQuery approved these changes

2023-07-11 09:45 UTC, TechQuery approved these changes

2023-07-11 09:45 UTC, merged