Img Carousel
kaiyuanshe/kaiyuanshe.github.io pull request #127
Opened 2023-07-10 08:36 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #123

2023-07-10 12:53 UTC, TechQuery requested changes

2023-07-10 12:53 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +        </Carousel>
1. 单张图片不轮播
2. 照片要居中

2023-07-11 09:05 UTC, TechQuery requested changes

2023-07-11 09:23 UTC, TechQuery requested changes

2023-07-11 09:23 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +                  style={{ height: '25rem', margin: 'auto' }}
```suggestion
                  className="m-auto object-fit-cover"
                  style={{ height: '25rem' }}
```

2023-07-11 09:27 UTC, luojiyin1987 commented on components/Activity/Agenda/Card.tsx
> +        mentorAvatars.length! > 1 ? (
```ts
mentorAvatars?.[1] ? (
```   有 元素隐式具有 "any" 类型，因为类型为 "1" 的表达式不能用于索引类型 的报错
我改成
```ts
Array.isArray(mentorAvatars) && mentorAvatars?.[1] ?
```

2023-07-11 10:58 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +        mentorAvatars.length! > 1 ? (
> ```ts
> mentorAvatars?.[1] ? (
> ```
> 
> 有 元素隐式具有 "any" 类型，因为类型为 "1" 的表达式不能用于索引类型 的报错 我改成
> 
> ```ts
> Array.isArray(mentorAvatars) && mentorAvatars?.[1] ?
> ```

断言一下就好：

```ts
(mentorAvatars as TableCellAttachment[])?.[1] ? (
```

2023-07-11 15:58 UTC, luojiyin1987 commented on components/Activity/Agenda/Card.tsx
> +          ))
从函数组件写成类组件？

2023-07-11 16:48 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +          ))
> 从函数组件写成类组件？ 

是的

2023-07-12 10:17 UTC, TechQuery requested changes

2023-07-12 10:17 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +  }
抽象首先要抽的是重复部分（`<Card.Img />`），你这样代码量不减反增。

而且我之前的 review 评论指向的代码段和我的描述都说的是“回调函数”部分抽出去，你这一整块是自己主动调用，不是回调（把函数传给另一个 API，让它在某些情况下来调用）。

2023-07-12 13:44 UTC, TechQuery requested changes

2023-07-12 13:44 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
>  export class AgendaCard extends Component<AgendaToolbarProps> {
你写的是普通函数，挂在类上才能叫“方法”：

```suggestion
@observer
export class AgendaCard extends Component<AgendaToolbarProps> {
  renderCardImage = (file: TableCellAttachment) => (
    <Card.Img
      key={file.attachmentToken}
      className="m-auto object-fit-cover"
      style={{ height: '25rem' }}
      loading="lazy"
      src={blobURLOf([file])}
    />
  );
```

2023-07-12 13:44 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +          )
```suggestion
          (mentorAvatars as unknown as TableCellAttachment[])?.map(this.renderCardImage)
```

2023-07-12 13:52 UTC, luojiyin1987 commented on components/Activity/Agenda/Card.tsx
>  export class AgendaCard extends Component<AgendaToolbarProps> {
原来想提高可调用性

2023-07-12 15:52 UTC, TechQuery requested changes

2023-07-12 15:52 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +  };
```suggestion
  renderCardImage = (file: TableCellAttachment) => (
      <Card.Img
        key={file.attachmentToken}
        className="m-auto object-fit-cover"
        style={{ height: '25rem' }}
        loading="lazy"
        src={blobURLOf([file])}
      />
    );
```

2023-07-12 15:52 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +            {(mentorAvatars as unknown as TableCellAttachment[])?.map(file => (
```suggestion
            {(mentorAvatars as unknown as TableCellAttachment[]).map(file => (
```

2023-07-12 15:53 UTC, TechQuery approved these changes

2023-07-12 19:29 UTC, merged