feat: volunteer page
kaiyuanshe/kaiyuanshe.github.io pull request #154
Opened 2023-08-28 03:20 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #151

2023-08-31 02:41 UTC, luojiyin1987 commented
@TechQuery    现在思路好像不对。

2023-08-31 10:23 UTC, TechQuery commented
> /model/person.ts  文件里没有对角色的定义。在多维表格里对 角色 的定义的字段是什么？ 

把字段名改成英文，你就查出来了：

![Screenshot_2023-08-31-18-22-15-044_com.ss.android.lark-edit.jpg](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/19969570/bfbaf27b-d6a8-4bf5-92c9-dde7d789d6c5)

2023-08-31 10:26 UTC, TechQuery requested changes

2023-08-31 10:26 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +  PersonStore?: PersonModel = undefined;
```suggestion
  personStore?: PersonModel = undefined;
```

2023-08-31 10:26 UTC, TechQuery commented on models/Activity.ts
> +import { PersonModel } from './Person';
这个模型链接的是整个开源社的人事数据库，不是活动数据库里的人员表。

2023-08-31 13:24 UTC, luojiyin1987 commented on models/Activity.ts
> +import { PersonModel } from './Person';
那从哪里导入 活动数据库里的人员表 ？

2023-08-31 14:30 UTC, TechQuery commented on models/Activity.ts
> +import { PersonModel } from './Person';
> 那从哪里导入 活动数据库里的人员表 ？ 难怪数据字段一直对不上

参考你写的 `BillModel`

2023-09-01 10:16 UTC, luojiyin1987 commented
@TechQuery   还是思路没打开。 person 的值没获取到。

2023-09-01 11:04 UTC, TechQuery commented
> @TechQuery   还是思路没打开。 person 的值没获取到。

因为 https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/154#discussion_r1311426341

2023-09-02 15:03 UTC, TechQuery commented on models/Activity.ts
> +import { PersonModel } from './Person';
> 那从哪里导入 活动数据库里的人员表 ？ 难怪数据字段一直对不上

我把 `/model` 整理了一下，便于你理解它们的区别：
1. #160
2. https://github.com/kaiyuanshe/kaiyuanshe.github.io#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD

2023-09-04 13:53 UTC, luojiyin1987 commented on models/Activity.ts
> +import { PersonModel } from './Person';
就是重新写个 activityPerson 的模型？

2023-09-04 15:10 UTC, TechQuery commented on models/Activity.ts
> +import { PersonModel } from './Person';
> 就是重新写个 activityPerson 的模型？

是这个意思，建议命名为 `model/Activity/Staff.ts`。

2023-09-06 10:51 UTC, TechQuery requested changes

2023-09-06 10:51 UTC, TechQuery commented on models/Activity/index.ts
> +      this.currentPerson = table.currentDataTable as PersonModel;
```suggestion
```

2023-09-08 14:09 UTC, luojiyin1987 commented
现在卡在如何过滤得到 list ，并如何从服务端传到客户端上。 @TechQuery

2023-09-08 15:41 UTC, TechQuery requested changes

2023-09-08 15:41 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +          </Table>
看清楚 issue 中的界面设计

2023-09-08 15:46 UTC, TechQuery requested changes

2023-09-08 15:46 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +    console.log('this.personStroe', this.staffStore);
```suggestion
    this.activityStore.currentStaff?.getAll();
```

2023-09-08 15:46 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +    console.log('personStore', list);
```suggestion
    const { activityStore } = this;
    const list = activityStore.currentStaff?.allItem;
```

2023-09-08 15:47 UTC, TechQuery commented
> 现在卡在如何过滤得到 list ，并如何从服务端传到客户端上。 @TechQuery  

你已经在客户端发请求了，没有服务端什么事。

具体查询方式详见后面的 review。

2023-09-10 10:26 UTC, TechQuery requested changes

2023-09-10 10:26 UTC, TechQuery commented on models/Activity/index.ts
> +      this.currentStaff = table.currentDataTable as unknown as StaffModel;
```suggestion
      this.currentStaff = table.currentDataTable as StaffModel;
```

2023-09-10 10:26 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +    );
```suggestion
    this.activityStore.currentStaff!.getAll({ role: '志愿者' });
  }

  renderVolunteers = ({ id, name }: Staff) => (
    <li
      key={id as string}
      className="d-flex flex-column align-items-center gap-2 position-relative"
    >
      <MemberCard name={name + ''} nickname={''} avatar={fileURLOf('')} />
    </li>
  );

  render() {
    const { activityStore } = this;
    const list = activityStore?.currentStaff?.allItems;
```

2023-09-11 14:35 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d94b54a02ff5bc3a6a4ebedf881dd4e45eb39217/pages/activity/%5Bid%5D/volunteer.tsx#L62C1-L83

不知道是  
```javascript
const grouped = groupBy(list , 'volunteerType'); 
```
是否正确

2023-09-11 18:47 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d94b54a02ff5bc3a6a4ebedf881dd4e45eb39217/pages/activity/%5Bid%5D/volunteer.tsx#L62-L83
> 
> 不知道是
> 
> ```js
> const grouped = groupBy(list , 'volunteerType'); 
> ```
> 
> 是否正确 @TechQuery
> 
> ```js
> grouped.map((item: Staff[]) => (
> ```
> 
> 报 此表达式不可调用。 类型 "Staff[]" 没有调用签名。

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/19969570/2ca6a2cc-b33e-4721-8e2e-cc1dd2b46323)
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/19969570/f94bcaeb-8c09-43c5-ae49-4364f2c4f659)

2023-09-11 18:48 UTC, TechQuery requested changes

2023-09-11 18:48 UTC, TechQuery commented on models/Activity/Staff.ts
> +  avatar: TableCellValue;
```suggestion
export type Staff = Record<'id' | 'name' | 'volunteerType' | 'avatar', TableCellValue> & {
```

2023-09-11 18:48 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +    const grouped = groupBy(list , 'volunteerType');
封装到模型层

2023-09-12 04:28 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/c3b0bf30a98a0dff22a7e06c9e50cd90411313fd/models/Activity/index.ts#L173-L174
还是报
```shell
类型 "ListModel<DataObject, Partial<NewData<DataObject>>> | undefined" 到类型 "StaffModel" 的转换可能是错误的，因为两种类型不能充分重叠。如果这是有意的，请先将表达式转换为 "unknown"。
  类型“ListModel<DataObject, Partial<NewData<DataObject>>>”缺少类型“StaffModel”的以下属性: requiredKeys, group, getGroup, sort 及其他 4 项。ts(2352)
```
@TechQuery

2023-09-12 10:59 UTC, TechQuery requested changes

2023-09-12 10:59 UTC, TechQuery commented on models/Activity/Staff.ts
> +  role: TableCellValue[];
```suggestion
  role: TableCellValue;
```

2023-09-12 10:59 UTC, TechQuery commented on models/Activity/Staff.ts
> +};
```suggestion
export type StaffFilter = Partial<NewData<Staff>>;
```

2023-09-12 10:59 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +    this.activityStore.currentStaff?.getAll({ role: '志愿者' });
```suggestion
    this.activityStore.currentStaff?.getGroup({ role: '志愿者' });
```

2023-09-12 11:00 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/c3b0bf30a98a0dff22a7e06c9e50cd90411313fd/models/Activity/index.ts#L173-L174
> 
> 还是报
> ```shell
> 类型 "ListModel<DataObject, Partial<NewData<DataObject>>> | undefined" 到类型 "StaffModel" 的转换可能是错误的，因为两种类型不能充分重叠。如果这是有意的，请先将表达式转换为 "unknown"。
>   类型“ListModel<DataObject, Partial<NewData<DataObject>>>”缺少类型“StaffModel”的以下属性: requiredKeys, group, getGroup, sort 及其他 4 项。ts(2352)
> ```

我也不明白 TS 此处的兼容性问题，但这么改就好了：https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/154#discussion_r1322865258

2023-09-12 14:57 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/eb7c914af9033359779c17793c2c756745fb0767/pages/activity/%5Bid%5D/volunteer.tsx#L50-L53

前端打开网页 `http://localhost:3000/activity/recNgZ1MiV/volunteer` 报
`Server Error
Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
` 
@TechQuery

2023-09-12 15:47 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/eb7c914af9033359779c17793c2c756745fb0767/pages/activity/%5Bid%5D/volunteer.tsx#L50-L53
> 
> 前端打开网页 `http://localhost:3000/activity/recNgZ1MiV/volunteer` 报
> `Server Error
> Error: [MobX] No annotations were passed to makeObservable, but no decorated members have been found either
> ` 
> 我也看了 [相关issue](https://github.com/mobxjs/mobx/issues/3225) , 好像没关系。

报错说：要么给 `makeObservable` 传注解参数，要么给类成员加装饰器。现在什么都没有，自然会报错。

也就是说类上面没声明任何可观察数据，这个函数就完全不需要调用。

2023-09-13 15:45 UTC, TechQuery requested changes

2023-09-13 15:45 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +      <MemberCard name={name + ''} nickname={''} avatar={blobURLOf(avatar)} />
```suggestion
      <MemberCard name={name + ''} nickname={''} avatar={fileURLOf(avatar)} />
```
没自动化缓存先用飞书接口

2023-09-13 15:45 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +        })}
```suggestion
        {Object.entries(staffGroup).map(([key, list]) => (
            <section key={key} id={key}>
              <MemberTitle
                className="my-5"
                title={key === 'undefined' ? '未分类志愿者' : key}
                count={list.length}
              />
              <ul className="list-unstyled d-flex flex-wrap gap-4">
                {list.map(this.renderVolunteers)}
              </ul>
            </section>
          ))}
```

2023-09-13 23:44 UTC, luojiyin1987 commented on pages/activity/[id]/volunteer.tsx
> +      <MemberCard name={name + ''} nickname={''} avatar={blobURLOf(avatar)} />
我原来用的就是 fileURLOf, 周会上你说用 blobURLOf

2023-09-14 08:42 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +      <MemberCard name={name + ''} nickname={''} avatar={blobURLOf(avatar)} />
> 我原来用的就是 fileURLOf, 周会上你说用 blobURLOf

不好意思，好几个功能我想串了，你这个地方现在是有缓存的。

2023-09-14 08:47 UTC, TechQuery requested changes

2023-09-14 08:47 UTC, TechQuery commented on pages/activity/[id]/volunteer.tsx
> +  staffGroup: StaffGroup;
```suggestion
interface VolunteerPageProps {
  activity: Activity;
  staffGroup: StaffModel['group'];
```

2023-09-14 09:07 UTC, TechQuery approved these changes

2023-09-14 09:07 UTC, merged

2023-09-14 13:45 UTC, TechQuery reviewed
如果数据库有数据，做完了要自测能否正常显示。

2023-09-14 13:45 UTC, TechQuery commented on models/Activity/Staff.ts
> +      ({ volunteerType }) => volunteerType + '',
这个字段在多维表格对应哪一列？

2023-09-14 14:06 UTC, luojiyin1987 commented on models/Activity/Staff.ts
> +      ({ volunteerType }) => volunteerType + '',
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/88523d24-614e-4d24-a416-a71b75a9e022)
在2023 cos 分成 offlineParticipation  和   onlineParticipation 字段里了

在 22 cos 中是  volunteerType 字段里   @TechQuery

2023-09-14 14:54 UTC, TechQuery commented on models/Activity/Staff.ts
> +      ({ volunteerType }) => volunteerType + '',
> 在2023 cos 分成 offlineParticipation 和 onlineParticipation 字段里了
> 
> 在 22 cos 中是 volunteerType 字段里 @TechQuery

2022 那个纯文本字段是谁建的？最终全都会和 2023 统一。