feature :add members photo wall
kaiyuanshe/kaiyuanshe.github.io pull request #165
Opened 2023-09-12 16:45 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #163

2023-09-12 17:04 UTC, TechQuery requested changes

2023-09-12 17:04 UTC, TechQuery commented on models/Organization/Cooperation.ts
为何改目录名？

2023-09-13 05:43 UTC, huoyueyuyuan commented on models/Organization/Cooperation.ts
额，写java写习惯了。
这些内容，最终是输出在 pages/organization 这里

2023-09-13 15:11 UTC, TechQuery requested changes
改了我再 review。

2023-09-13 15:11 UTC, TechQuery commented on models/Organization/Cooperation.ts
> 额，写java写习惯了。
> 这些内容，最终是输出在 pages/organization 这里

不都是，还有 cooperation。

2023-09-14 09:05 UTC, TechQuery requested changes

2023-09-14 09:05 UTC, TechQuery commented on models/Community/index.ts
> +      Activity: (Activity as TableCellRelation[])?.map(normalizeText)[0],
```suggestion
  | 'logo'
  | 'director'
  | 'startDate'
  | 'summary'
  | 'link',
  TableCellValue
>;

export const KCC_BASE_ID = process.env.NEXT_PUBLIC_KCC_BASE_ID!;
export const COMMUNITY_TABLE_ID = process.env.NEXT_PUBLIC_COMMUNITY_TABLE_ID!;

export class CommunityModel extends BiDataTable<Community>() {
  client = larkClient;

  constructor(appId = KCC_BASE_ID, tableId = COMMUNITY_TABLE_ID) {
    super(appId, tableId);

    makeObservable(this);
  }

  requiredKeys = ['name'] as const;

  sort = { name: 'ASC' } as const;

  @observable
  group: Record<string, Community[]> = {};

  normalize({
    id,
    fields: { link, director, ...fields },
  }: TableRecord<Community>) {
    return {
      ...fields,
      id: id!,
      link: (link as TableCellLink)?.link,
      director: (director as TableCellRelation[])?.map(normalizeText)[0],
```
双向关联表自动生成的字段就不用管。

2023-09-14 09:05 UTC, TechQuery commented on pages/community/[community].tsx
> +    <PageHead title={`${community}社区`} />
翻译

2023-09-14 09:05 UTC, TechQuery commented on pages/community/[community].tsx
> +      <h3 className="my-5 text-center">{t('add_member')}</h3>
此处可以把多维表格生成的表单链接在此，用于报名。

2023-09-14 09:05 UTC, TechQuery commented on pages/community/index.tsx
> +    const list = await new CommunityModel().getList();
```suggestion
    const list = await new CommunityModel().getAll();
```

2023-09-14 09:05 UTC, TechQuery commented on pages/community/[community].tsx
> +    const list = await new CommunityMemberModel().getList({ community });
```suggestion
    const list = await new CommunityMemberModel().getAll({ community });
```

2023-09-14 09:17 UTC, TechQuery commented
顺便加一下 KCC 社区搜索，成员先不管。参考代码从此按图索骥：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/7e50612b7ce872e4517d346d4f595177631ae4ae/pages/search/index.tsx#L79-L81

2023-09-14 09:45 UTC, d-ethan3 commented on pages/community/[community].tsx
> +      <h3 className="my-5 text-center">{t('add_member')}</h3>
Communtity, Person, Activity 每个表格都要生成一个表单吗？

2023-09-14 09:53 UTC, TechQuery commented on pages/community/[community].tsx
> +      <h3 className="my-5 text-center">{t('add_member')}</h3>
> Communtity, Person, Activity 每个表格都要生成一个表单吗？

可以，参考 COSCon 数据库的表单

2023-09-14 14:05 UTC, TechQuery requested changes

2023-09-14 14:05 UTC, TechQuery commented on pages/community/[community].tsx
> +    )}
```suggestion
  <section className="my-5 text-center">
    {list[0] ? (
      <>
        <h2 className="mb-5">{t('community_member')}</h2>
        <CommunityMemberList list={list} />
      </>
    ) : (
        <h2>{t('add_member')}</h2>
    )}
        <Button
          size="lg"
          href="https://kaiyuanshe.feishu.cn/share/base/form/shrcnogj5LPzlaiUkFaKpVbxNXe">
          {t('member_register')}
        </Button>
      </section>
```
1. 除了文章内容，布局不要用 `<br />`。
2. 社区成员页只显示成员申请表，社区成立申请表只能放在社区列表页，活动发起表暂时不放出来，只给社区组织者用。

2023-09-14 15:17 UTC, TechQuery submitted a review, later dismissed

2023-09-14 15:20 UTC, TechQuery approved these changes

2023-09-14 15:20 UTC, merged