[optimize]: show agenda file
kaiyuanshe/kaiyuanshe.github.io pull request #181
Opened 2023-09-21 09:51 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #131

2023-09-21 15:47 UTC, TechQuery requested changes

2023-09-21 15:47 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +    <Col>资料下载</Col>
国际化翻译

2023-09-21 15:47 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +  </Row>
```suggestion
  <section>
    <h2>资料下载</h2>
    <ol>
    {fileInfo.map(({ id, name, attachmentToken }) => (
      <li key={id + ''}>
        <FilePreview path={`/api/lark/file/${attachmentToken}`} />
      </li>
    ))}
    </ol>
  </section>
```

2023-09-21 15:47 UTC, TechQuery commented on models/Activity/Agenda.ts
> +};
因为类型推导的一些兼容性问题，我们统一使用一样的字段类型。

2023-09-21 15:47 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> ->(cache(), router, errorLogger, translator(i18n), async ({ params }) => {
上线前要把它还原。

2023-09-21 15:47 UTC, TechQuery commented on models/Activity/AgendaFile.ts
> +export const COMMUNITY_TABLE_ID = 'tblUOAb6Q1r0WR8s';
测试用的 ID 可以临时写一个 `.env.development.local` 配置文件

2023-09-21 15:47 UTC, TechQuery commented on models/Activity/AgendaFile.ts
> +  [x: string]: any;
```suggestion
```

2023-09-21 15:47 UTC, TechQuery commented on models/Activity/AgendaFile.ts
> +  group: Record<string, AgendaFile[]> = {};
```suggestion
  }

  requiredKeys = ['summary'] as const;

  sort = { summary: 'ASC' } as const;
```
没有分组需求，你也没写分组方法，就完全不需要这些。

2023-09-21 19:02 UTC, huoyueyuyuan commented on models/Activity/AgendaFile.ts
> +export const COMMUNITY_TABLE_ID = 'tblUOAb6Q1r0WR8s';
models/Activity/AgendaFile.ts 这个文件， 其实已经用不到。 建议上线前删除。

2023-09-22 00:39 UTC, d-ethan3 commented on models/Activity/AgendaFile.ts
> +export const COMMUNITY_TABLE_ID = 'tblUOAb6Q1r0WR8s';
> Member

好的

2023-09-22 06:39 UTC, d-ethan3 commented on components/Activity/Agenda/FileList.tsx
> +  </Row>
这里我只将⌈资料下载⌋改为了 <h2>

2023-09-22 12:12 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +  </Row>
> 这里我只将⌈资料下载⌋改为了 ⌈h2⌋ 标签

都要改：
1. 一行一列的没必要用**布局组件**
2. 列表要**语义化**

2023-09-22 12:16 UTC, TechQuery requested changes
之前还有没改的

2023-09-22 17:48 UTC, TechQuery requested changes

2023-09-22 17:48 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +        </a>
```suggestion
export const FileList: FC<{ data: TableCellAttachment[] }> = ({ data }) => (
  <Row as="section" className="justify-content-center" xs={1}>
    <h2>{t('data_download')}</h2>
    {data.map(({ id, name, mimeType, attachmentToken }) => (
      <Col key={id + ''}>
        <FilePreview type={mimeType} path={`/api/lark/file/${attachmentToken}`} />
        <Badge bg="success">{name}</Badge>
```
此处只演示**文件预览**，其它该改的还要改。

2023-09-23 07:40 UTC, TechQuery requested changes

2023-09-23 07:40 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +);
```suggestion
export const FileList: FC<{ data: TableCellAttachment[] }> = observer (({ data }) => (
  <section>
    <h2>{t('file_download')}</h2>
    <ol>
      {data.map(({ id, name, mimeType, attachmentToken }) => (
        <li key={id + ''}>
          <FilePreview
            type={mimeType}
            path={`/api/lark/file/${attachmentToken}`}
          />
          <Badge>{name}</Badge>
        </li>
      ))}
    </ol>
  </section>
));
```
用了 MobX-i18n 提供的可观察数据的组件，也要变成观察者。

2023-09-24 08:56 UTC, TechQuery requested changes

2023-09-24 08:56 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +            <Badge>{name}</Badge>
参考以下代码，根据文本内容生成多彩背景：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/5d7d4aaa87f019feff8dc497df0433c4b79de9ca/components/Article/Card.tsx#L54

2023-09-24 09:16 UTC, TechQuery requested changes

2023-09-24 09:16 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +              bg={text2color(name,['light'])}
你应该不是在本地改的吧？既没有格式化，也没有导入这个工具函数。

2023-09-24 09:18 UTC, d-ethan3 commented on components/Activity/Agenda/FileList.tsx
> +              bg={text2color(name,['light'])}
我在手机上改的，我现在在电影院，回去改

2023-09-24 12:29 UTC, TechQuery requested changes

2023-09-24 12:29 UTC, TechQuery commented on components/Activity/Agenda/FileList.tsx
> +);
```suggestion
export const FileList: FC<{ data: TableCellAttachment[] }> = observer(
  ({ data }) => (
    <section>
      <h2>{t('file_download')}</h2>
      <ol>
        {data.map(({ id, name, mimeType, attachmentToken }) => (
          <li key={id + ''}>
            <FilePreview
              type={mimeType}
              path={`/api/lark/file/${attachmentToken}`}
            />

            <Badge bg={text2color(name, ['light'])}>{name}</Badge>
          </li>
        ))}
      </ol>
    </section>
  ),
);
```

2023-09-24 12:33 UTC, TechQuery approved these changes

2023-09-24 12:34 UTC, merged