[optimize]: add activity articles calendar
kaiyuanshe/kaiyuanshe.github.io pull request #183
Opened 2023-09-22 09:24 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #113

2023-09-22 15:37 UTC, TechQuery requested changes

2023-09-22 15:37 UTC, TechQuery commented on pages/calendar/index.tsx
> +        const date = new Date(Number(publishedAt!.valueOf()));
```suggestion
        const date = new Date(publishedAt as number);
```

2023-09-22 15:37 UTC, TechQuery commented on pages/calendar/index.tsx
> +          : accumulator.push({ date, content: title + '' });
```suggestion
        if (index > -1)
          accumulator[index].content += `\n${title}`;
        else
          accumulator.push({ date, content: title + '' });
```
不使用值的时候不需要表达式，用语句。

2023-09-22 17:19 UTC, TechQuery requested changes

2023-09-22 17:19 UTC, TechQuery commented on pages/calendar/index.tsx
> +    );
1. 数据整理逻辑放在 Model 侧，写成一个 getter 方法
2. 因为要随着用户翻月份来查询当月活动，所以需要把服务端取数据改到客户端，示例如下：

```tsx
@observer
export default class CalendarPage extends PureComponent {
  store = new SearchArticleModel();

  componentDidMount() {
    this.loadData();
  }

  loadData(month?: number) {
    return this.store.getMonthList({ tags: '活动' }, month);
  }

  render() {
    const { currentMonthList } = this.store;

    return <MonthCalendar
      value={currentMonthList}
      onChange={date => this.loadData(date.getMonth() + 1)}
    />;
  }
}
```

（以上代码需升级组件库：https://github.com/idea2app/Idea-React/releases/tag/v1.0.0-rc.26）

2023-09-24 22:13 UTC, TechQuery requested changes

2023-09-24 22:13 UTC, TechQuery commented on models/Product/Article.ts
> +        `CurrentValue.[publishedAt]>=TODATE("2022-${currentDate.getMonth()}-01")`,
```suggestion
import { Filter } from 'mobx-restful';

export class CalendarSearchArticleModel extends ArticleModel {
  currentDate?: Date;

  async getMonthList(filter: Filter<Article>, date = new Date()) {
    this.currentDate = date;

    try {
      this.clearList();

      return await this.getAll(filter);
    } finally {
      this.currentDate = undefined;
    }
  }

  makeFilter({ ...filter }: NewData<Article>) {
    const [year, month] =
      this.currentDate?.toJSON().split('T')[0].split('-') || [];
    const nextMonth = (+month + 1 + '').padStart(2, '0');

    return [
      year && `CurrentValue.[publishedAt]>=TODATE("${year}-${month}-01")`,
      year && `CurrentValue.[publishedAt]<TODATE("${year}-${nextMonth}-01")`,
```

2023-09-24 22:13 UTC, TechQuery commented on pages/calendar/index.tsx
> +  }
```suggestion
  store = new CalendarSearchArticleModel();

  componentDidMount() {
    this.loadData();
  }

  loadData = (date?: Date) => this.store.getMonthList({ tags: '活动' }, date);
```

2023-09-24 22:13 UTC, TechQuery commented on pages/calendar/index.tsx
> +        ) : null}
```suggestion
    const { downloading, allItems } = this.store;

    return (
      <Container className="py-5 text-center">
        <PageHead title={t('activity_articles_calendar')} />
        <h1 className="mb-5 text-center">{t('activity_articles_calendar')}</h1>

        {downloading > 0 && <Loading />}

        <MonthCalendar
          value={allItems.map(({ id, title, publishedAt, alias }) => ({
            date: new Date(publishedAt as number),
            content: (
              <OverlayBox title={title}>
                <Badge
                  className="d-inline-block text-truncate"
                  bg={text2color(title, ['light'])}
                  as="a"
                  href={`/article/${alias}`}
                  target="_blank"
                  rel="noreferrer"
                >
                  {title}
                </Badge>
              </OverlayBox>
            ),
          }))}
          onChange={this.loadData}
        />
        {allItems[0] && (
          <section>
            <h2>{t('article')}</h2>
            <ArticleListLayout defaultData={allItems} />
          </section>
        )}
```

2023-09-25 06:56 UTC, TechQuery requested changes

2023-09-25 06:56 UTC, TechQuery commented on components/data.ts
> +      { title: t('activity_articles_calendar'), path: '/calendar' },
```suggestion
      { title: t('activity_articles_calendar'), path: '/activity/calendar' },
```
我觉得把它作为“精彩活动”的一个子菜单“活动日历”比较好，原有的链接变为“主办活动”子菜单。

2023-09-25 06:56 UTC, TechQuery commented on models/Product/Article.ts
> +    return [
```suggestion
    const nextMonth = (+month + 1 + '').padStart(2, '0');

    return [
```

2023-09-25 06:56 UTC, TechQuery commented on pages/calendar/index.tsx
> +        <MonthCalendar
```suggestion
  store = new CalendarSearchArticleModel();

  componentDidMount() {
    this.loadData();
  }

  loadData = (date?: Date) => this.store.getMonthList({ tags: '活动' }, date);

  render() {
    const { downloading, allItems } = this.store;

    return (
      <Container className="py-5 text-center">
        <PageHead title={t('activity_articles_calendar')} />

        <h1 className="mb-5 text-center">{t('activity_articles_calendar')}</h1>

        {downloading > 0 && <Loading />}

        <MonthCalendar
```
保留必要空行，以增强可读性。

2023-09-25 07:34 UTC, TechQuery requested changes

2023-09-25 07:38 UTC, TechQuery approved these changes

2023-09-25 07:39 UTC, huoyueyuyuan commented on models/Product/Article.ts
> +      await this.getAll(filter);
我看是从 allItems取， 还特意删除了  return 。
已经加回 。

2023-09-25 07:40 UTC, merged