[add] homepage activity card
kaiyuanshe/kaiyuanshe.github.io pull request #185
Opened 2023-09-22 13:21 UTC by wangrunlin

Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #180

2023-09-22 17:26 UTC, TechQuery requested changes

2023-09-22 17:26 UTC, TechQuery commented on pages/index.tsx
>              <h2 className="my-5 text-center text-primary">最新活动</h2>
国际化翻译

2023-09-22 17:26 UTC, TechQuery commented on pages/index.tsx
> +        <section className="text-center bg-primary">
```suggestion
        <header className="text-center bg-primary">
```

2023-09-22 17:26 UTC, TechQuery commented on pages/index.tsx
> +          </Carousel>
独立为类方法

2023-09-22 17:26 UTC, TechQuery commented on pages/index.tsx
> +                </Carousel.Caption>
```suggestion
                <Carousel.Caption as="h3">
                    <a
                      className="stretched-link text-decoration-none text-dark"
                      href={database ? `/activity/${id}` : link + ''}
                    >
                      {name}
                    </a>
                </Carousel.Caption>
```

2023-09-23 07:48 UTC, TechQuery requested changes

2023-09-23 07:48 UTC, TechQuery commented on pages/index.tsx
> +  { articles: Article[]; activity: Activity[]; projects: Department[] }
```suggestion
  { articles: Article[]; activities: Activity[]; projects: Department[] }
```

2023-09-23 07:48 UTC, TechQuery commented on pages/index.tsx
> +  }) => (
`Record`

2023-09-23 07:48 UTC, TechQuery commented on pages/index.tsx
> +          target={(link + '').startsWith('http') ? '_blank' : '_self'}
https://web-cell.dev/web-utility/functions/isXDomain.html

2023-09-23 17:08 UTC, wangrunlin commented on pages/index.tsx
> +          target={(link + '').startsWith('http') ? '_blank' : '_self'}
`SSR` 无法使用 `document`

2023-09-23 22:54 UTC, TechQuery approved these changes

2023-09-24 12:54 UTC, TechQuery requested changes

2023-09-24 12:54 UTC, TechQuery commented on pages/index.tsx
> +          fluid
```suggestion
          fluid
          src={image}
```

2023-09-24 12:54 UTC, TechQuery commented on pages/index.tsx
> +                fluid
```suggestion
                style={{ height: '90vh' }}
                fluid
                src="/image/Heart_of_Community.png"
                alt="Head Image"
```

2023-09-24 13:19 UTC, TechQuery requested changes

2023-09-24 13:19 UTC, TechQuery commented on styles/Home.module.less
>  }
和上面可以合并成一条嵌套规则。

2023-09-24 13:39 UTC, TechQuery approved these changes

2023-09-24 13:40 UTC, merged