[add] activity add alias path
kaiyuanshe/kaiyuanshe.github.io pull request #188
Opened 2023-09-22 16:29 UTC by wangrunlin

Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [x] Reviewers

- Closes #186

2023-09-22 17:02 UTC, TechQuery requested changes

2023-09-22 17:02 UTC, TechQuery commented on models/Activity/index.ts
> +    const currentOne = item ? this.normalize(item) : await super.getOne(alias);
现在活动**跨表查询**已经很慢了，再多一个通过查列表的接口来查单条，访问频次低、无缓存的议程相关页面首次访问会更慢。

所以建议 ID 优先，别名只做兼容。

2023-09-23 04:59 UTC, wangrunlin commented
> ```suggestion
    const [item] = body!.data!.items;
``` 

我打印过日志，`items` 不一定存在

2023-09-23 07:50 UTC, TechQuery commented
> > ```suggestion
> >     const [item] = body!.data!.items;
> > ``` 
> 
> 我打印过日志，`items` 不一定存在

```suggestion
    const [item] = body!.data!.items || [];
```

2023-09-23 22:52 UTC, TechQuery approved these changes

2023-09-23 22:54 UTC, merged