[optimize]: add add previous activity Button
kaiyuanshe/kaiyuanshe.github.io pull request #192
Opened 2023-09-26 13:35 UTC by huoyueyuyuan

Checklist（清单）:

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #191

2023-09-26 16:53 UTC, TechQuery requested changes

2023-09-26 16:53 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +          <Button variant="success" href={`/search?keywords=收官`}>
```suggestion
          <Button variant="success" href="/search?keywords=收官">
```

2023-09-26 16:53 UTC, TechQuery commented on translation/en-US.ts
> +  previous_activity: 'Previous Activity',
```suggestion
  previous_activities: 'Previous Activities',
```

2023-09-27 02:12 UTC, wangrunlin submitted a review, later dismissed

2023-09-27 09:35 UTC, TechQuery approved these changes

2023-09-27 10:32 UTC, merged