Project list page
kaiyuanshe/kaiyuanshe.github.io pull request #194
Opened 2023-09-28 09:53 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #193

2023-09-30 08:25 UTC, luojiyin1987 commented
preject页 在首页还没入口 url

2023-09-30 23:47 UTC, TechQuery commented
> preject页 在首页还没入口 url

放到主导航栏「开源项目」菜单中，并且在主页我们的项目下面加一个「更多项目」按钮。

2023-10-01 01:46 UTC, luojiyin1987 commented
> 更多项目

已经添加

2023-10-01 12:59 UTC, TechQuery requested changes

2023-10-01 12:59 UTC, TechQuery commented on models/Repository.ts
> +const getGitLanges = memoize(async (URI: string) => {
```suggestion
const getGitLanguages = memoize(async (URI: string) => {
```

2023-10-01 12:59 UTC, TechQuery commented on models/Repository.ts
> +        return { ...item, full_name, issues, languages };
```suggestion
        const languages = await getGitLanges(full_name);

        return { ...item, full_name, issues, languages };
```

2023-10-01 13:33 UTC, luojiyin1987 commented on models/Repository.ts
> +import { averageOf,buildURLData } from 'web-utility';
原来代码里 已经使用  `averageOf`   了， 什么格式化代码没执行？

2023-10-01 16:53 UTC, TechQuery commented on models/Repository.ts
> +import { averageOf,buildURLData } from 'web-utility';
> 原来代码里 已经使用 `averageOf` 了， 什么格式化代码没执行？

看上面我更新的

2023-10-01 16:56 UTC, TechQuery commented on translation/en-US.ts
> +  project_list: 'more project',
这个没改完，仔细比对

2023-10-01 16:57 UTC, TechQuery commented on models/Repository.ts
> +        return { ...item, full_name, issues, languages };
这是你本地格式化脚本出 bug 了，还是没改？

2023-10-02 01:26 UTC, luojiyin1987 commented on models/Repository.ts
> +        return { ...item, full_name, issues, languages };
当时网络不太好， 有些延时。  改了，提交了几次。

2023-10-02 01:30 UTC, luojiyin1987 commented on models/Repository.ts
> +import { averageOf,buildURLData } from 'web-utility';
应该是那一次没运行成功

2023-10-02 01:31 UTC, luojiyin1987 commented on translation/en-US.ts
> +  project_list: 'more project',
当时改了， 提交几次没成功

2023-10-02 10:36 UTC, TechQuery approved these changes

2023-10-02 10:36 UTC, merged