add: add recommend agenda list
kaiyuanshe/kaiyuanshe.github.io pull request #204
Opened 2023-10-05 06:25 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #202

2023-10-05 09:26 UTC, TechQuery requested changes

2023-10-05 09:26 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> +      { score,recommends } = this.props;
```suggestion
      { score, recommends } = this.props;
```
格式化脚本没有正常执行。

2023-10-05 09:26 UTC, TechQuery commented on models/Activity/Agenda.ts
>    }
此处还原，都不需要改变。

2023-10-05 09:26 UTC, TechQuery commented on models/Activity/Agenda.ts
> +  constructor(appId = COSCon_2023, tableId = COSCon_2023_AGENDA_ID) {
```suggestion
  constructor(public appId: string, public tableId: string) {
```

2023-10-05 09:26 UTC, TechQuery commented on models/Activity/Agenda.ts
> +      forum,
```suggestion
  async getOne(id: string) {
    await super.getOne(id);

    const { title } = this.currentOne;

    this.currentRecommend = new SearchAgendaModel(this.appId, this.tableId);

    await this.currentRecommend!.getList({
      title: words  // 分词逻辑自己写
```
1. 因安全原因，本项目的中文字段仅用于提交给飞书 API 筛选，不会包含在返回数据中。
2. 分词 API：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter

2023-10-05 12:00 UTC, TechQuery requested changes

2023-10-05 12:00 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> +            )}
放到“观众评分”下面

2023-10-05 12:00 UTC, TechQuery commented on models/Activity/Agenda.ts
> +      mentors,
```suggestion
    const { title } = this.currentOne;

    this.currentRecommend = new SearchAgendaModel(this.appId, this.tableId);

    const segmenter = new Intl.Segmenter('zh', { type: 'word' });

    const segments = segmenter.segment(title + '');

    const words = Array.from(segments, ({ segment }) => segment);  // 还可以根据词性过滤一下，去掉一些无意义的辅助词

    await this.currentRecommend!.getList({
```

2023-10-05 12:19 UTC, huoyueyuyuan commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> +            )}
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/50b62991-2a6c-439b-b668-58b29820fbca)
这个是放到观众评分下效果

2023-10-05 12:35 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> +            )}
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/50b62991-2a6c-439b-b668-58b29820fbca)
> 这个是放到观众评分下效果

我在群里还说了“把评论框放在左栏”

2023-10-05 18:17 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> +                      <Col as="li" key={agenda.id + ''}>
```suggestion
                    .map(agenda => agenda.title !== title && (
                      <Col as="li" key={agenda.id + ''}>
```
JSX 会忽略假值，如上可减少遍历次数。

2023-10-06 18:36 UTC, TechQuery requested changes

2023-10-06 18:36 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
>            </Col>
```suggestion
          <Col xs={12} sm={9}>
            <main className="my-4">{summary + ''}</main>

            {fileInfo && <FileList data={fileInfo} />}

            <div className="my-5">
              <CommentBox
                category="General"
                categoryId="DIC_kwDOB88JLM4COLSV"
              />
            </div>
          </Col>
          {recommends[0] && (
            <Col xs={12} sm={3} as="section" id="related_agenda">
              <h2 className="my-3">{t('related_agenda')}</h2>

              <ol className="list-unstyled d-flex flex-column gap-4">
                {recommends.map(
                  agenda =>
                    agenda.title !== title && (
                      <li key={agenda.id + ''}>
                        <AgendaCard
                          activityId={id + ''}
                          location={location + ''}
                          {...agenda}
                        />
                      </li>
                    ),
                  )}
              </ol>
            </Col>
          )}
```

2023-10-06 18:38 UTC, TechQuery approved these changes

2023-10-06 18:40 UTC, merged