Fix GitHub api limit
kaiyuanshe/kaiyuanshe.github.io pull request #205
Opened 2023-10-06 15:43 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #200

2023-10-06 15:46 UTC, luojiyin1987 commented
看看抄写的的对不对？  然后明天还要改  `githubClient`  请求的 `baseURI` 。 @TechQuery

2023-10-06 15:49 UTC, TechQuery requested changes

2023-10-06 15:49 UTC, TechQuery commented on pages/api/github/core.ts
> +    const { status, body:data} = await githubClient.get(path);
`method` 不能写死

2023-10-06 15:49 UTC, TechQuery commented on pages/api/github/core.ts
> +  safeAPI(async ({  url, headers }, response) => {
格式化没执行

2023-10-07 03:41 UTC, luojiyin1987 commented
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/1bf6a09a-b0a5-44a4-84cb-458e3963fc18)
```shell
curl -vvv -X get http://localhost:3000/api/github/repos/kaiyuanshe/
KYS-service/languages
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> get /api/github/repos/kaiyuanshe/KYS-service/languages HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Connection: close
<
* Closing connection 0
```
试了一上午 还是没调通  @TechQuery

2023-10-07 10:33 UTC, TechQuery commented
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/1bf6a09a-b0a5-44a4-84cb-458e3963fc18)
> ```shell
> curl -vvv -X get http://localhost:3000/api/github/repos/kaiyuanshe/
> KYS-service/languages
> Note: Unnecessary use of -X or --request, GET is already inferred.
> *   Trying 127.0.0.1:3000...
> * Connected to localhost (127.0.0.1) port 3000 (#0)
> > get /api/github/repos/kaiyuanshe/KYS-service/languages HTTP/1.1
> > Host: localhost:3000
> > User-Agent: curl/7.81.0
> > Accept: */*
> >
> * Mark bundle as not supporting multiuse
> < HTTP/1.1 400 Bad Request
> < Connection: close
> <
> * Closing connection 0
> ```
> 试了一上午 还是没调通  @TechQuery 

那是因为你根本就没有定义这个接口，只定义了代理工具函数的实现……

2023-10-07 11:40 UTC, luojiyin1987 commented
> > ![image](https://user-images.githubusercontent.com/6524977/273361228-1bf6a09a-b0a5-44a4-84cb-458e3963fc18.png)
> > ```shell
> > curl -vvv -X get http://localhost:3000/api/github/repos/kaiyuanshe/
> > KYS-service/languages
> > Note: Unnecessary use of -X or --request, GET is already inferred.
> > *   Trying 127.0.0.1:3000...
> > * Connected to localhost (127.0.0.1) port 3000 (#0)
> > > get /api/github/repos/kaiyuanshe/KYS-service/languages HTTP/1.1
> > > Host: localhost:3000
> > > User-Agent: curl/7.81.0
> > > Accept: */*
> > >
> > * Mark bundle as not supporting multiuse
> > < HTTP/1.1 400 Bad Request
> > < Connection: close
> > <
> > * Closing connection 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试了一上午 还是没调通  @TechQuery
> 
> 那是因为你根本就没有定义这个接口，只定义了代理工具函数的实现……

好吧，我当时以为有文件就会自动加载，生成 api 的路径，因为返回信息里有 GitHub 相关。 后来声明了一个 slug.ts 文件

2023-10-07 11:50 UTC, TechQuery commented
> 好吧，我当时以为有文件就会自动加载，生成 api 的路径，因为返回信息里有 GitHub 相关。 后来声明了一个 slug.ts 文件

不要“以为”，要看文档：https://nextjs.org/docs/pages/building-your-application/routing/api-routes

2023-10-07 12:00 UTC, luojiyin1987 commented
> > 好吧，我当时以为有文件就会自动加载，生成 api 的路径，因为返回信息里有 GitHub 相关。 后来声明了一个 slug.ts 文件
> 
> 不要“以为”，要看文档：https://nextjs.org/docs/pages/building-your-application/routing/api-routes

https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes   我从这个去理解了

2023-10-07 14:07 UTC, TechQuery commented
> > > 好吧，我当时以为有文件就会自动加载，生成 api 的路径，因为返回信息里有 GitHub 相关。 后来声明了一个 slug.ts 文件
> > 
> > 不要“以为”，要看文档：https://nextjs.org/docs/pages/building-your-application/routing/api-routes
> 
> https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes   我从这个去理解了

这边也有：https://nextjs.org/docs/pages/building-your-application/routing/api-routes#dynamic-api-routes

2023-10-16 14:20 UTC, TechQuery requested changes

2023-10-16 14:20 UTC, TechQuery commented on pages/api/github/core.ts
> +    console.log('proxyGithub path: ', path);
```suggestion

```

2023-10-16 14:20 UTC, TechQuery commented on pages/api/github/[...slug].ts
> +});
```suggestion
export default proxyGithub((path, data) => data);
```

2023-10-17 10:23 UTC, TechQuery requested changes

2023-10-17 10:23 UTC, TechQuery commented on models/Base/index.ts
> +});
```suggestion
```
不需要专门的客户端，代码都是前后端共用的，在初始化的时候判断环境填入不同的 `baseURI` 即可。

2023-10-17 11:37 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/26332239df498faff98f79d51e4f1a638aa734d9/models/Repository.ts#L34-L39

38行 的 baseURI 变量很容易引起困惑， 再加上后面的  this.baseURI
 https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/26332239df498faff98f79d51e4f1a638aa734d9/models/Repository.ts#L93-L100

2023-10-17 18:25 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/26332239df498faff98f79d51e4f1a638aa734d9/models/Repository.ts#L34-L39
> 
> 38行 的 baseURI 变量很容易引起困惑， 再加上后面的 this.baseURI
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/26332239df498faff98f79d51e4f1a638aa734d9/models/Repository.ts#L93-L100

我 https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/205#discussion_r1361878818 建议的是将以下代码：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/81e89606d2975a1308c1894efc2cff17af454eb0/models/Base/index.ts#L42-L45

改为

```ts
 export const githubClient = new HTTPClient({ 
   baseURI: isServer ? 'https://api.github.com/' : `${API_Host}/api/github/`,
   responseType: 'json',
 }).use(({ request }, next) => {
```

2023-10-18 03:59 UTC, TechQuery requested changes

2023-10-18 03:59 UTC, TechQuery commented on models/Base/index.ts
> +  if (isServer() && GithubToken)
此处不用变更，把环境变量名删去 `NEXT_PUBLIC_` 前缀，前端就读不到了。

2023-10-18 03:59 UTC, TechQuery commented on models/Repository.ts
> +import { HTTPClient } from 'koajax';
```suggestion
```

2023-10-18 04:30 UTC, TechQuery approved these changes

2023-10-18 04:30 UTC, merged