fix：update agenda card layout
kaiyuanshe/kaiyuanshe.github.io pull request #219
Opened 2023-10-15 16:19 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #206

2023-10-15 17:10 UTC, TechQuery requested changes

2023-10-15 17:10 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +          </Row>
```suggestion
                <ActivityPeople
                  size={6}
                  names={mentors as string[]}
                  avatars={
                      (mentorAvatars as TableCellValue[]).map(blobURLOf)
                   }
                />
```

2023-10-15 17:10 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +            <Col as="li" className="text-center">
```suggestion
          <ul className="list-unstyled">
            <li className="text-center">
```
单列没必要用布局框。

2023-10-15 17:10 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +              })}
这个方法本来就是自动判断用户语言来生成本地化的日期文字，你写死语言就本末倒置了。

2023-10-15 17:10 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +            </Col>
```suggestion
            {score && <li>
              <ScoreBar value={score + ''} />
            </li>}
```

2023-10-15 17:13 UTC, huoyueyuyuan commented on components/Activity/Agenda/Card.tsx
> +          </Row>
如果按这么写， 图片只会横向排列。

2023-10-15 17:46 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +          </Row>
> 如果按这么写， 图片只会横向排列。

给组件加个 `className` 的 props，由外面传 `flex-column` 类：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/7d2fa7347a91b2a1c054306881ce1fbd29d7fe90/components/Activity/People.tsx#L6-L16

2023-10-16 14:24 UTC, TechQuery requested changes

2023-10-16 14:24 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +            <li className="m-1">
```suggestion
          <ul className="list-unstyled d-flex flex-column gap-1 justify-content-center h-100">
            <li>
```

2023-10-16 14:24 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +        style={{ height: '18rem' }}
```suggestion
        className="list-unstyled border border-light rounded m-2 h-100"
```

2023-10-16 14:58 UTC, TechQuery requested changes

2023-10-16 14:58 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +      className="card-img-top m-auto object-fit-cover"
```suggestion
      rounded
      className="m-auto object-fit-cover"
```

2023-10-16 14:58 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +                    />
```suggestion
        <Col as="li" className="col-4 d-flex justify-content-center align-items-center">
          {(mentors as string[])?.[1] ? (
              <Carousel>
                {(mentorAvatars as TableCellAttachment[]).map(file => (
                  <Carousel.Item key={file.attachmentToken}>
                    {this.renderCardImage(file)}
```

2023-10-16 19:41 UTC, TechQuery approved these changes

2023-10-16 19:43 UTC, merged