update: license filter
kaiyuanshe/kaiyuanshe.github.io pull request #221
Opened 2023-10-16 15:19 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #176

2023-10-16 15:22 UTC, luojiyin1987 commented
https://kaiyuanshe.feishu.cn/wiki/Wi4twa199iCW9MkjiJfcmE8cnMf?from=from_copylink   
先更新补充说明的文字。

@TechQuery   @tedliu1

2023-10-16 15:35 UTC, TechQuery requested changes
繁体中文也要同步

2023-10-16 15:35 UTC, TechQuery commented on translation/zh-CN.ts
> +    '您是否希望将结果限制在开放源代码促进会 (Open Source Initiative,缩写:OSI)所描述的 "流行、广泛使用或拥有强大社群” 的许可证上？',
```suggestion
    '您是否希望将结果限制在开放源代码促进会（Open Source Initiative，缩写：OSI）所描述的 "流行、广泛使用或拥有强大社群” 的许可证上？',
```

2023-10-17 10:18 UTC, TechQuery approved these changes

2023-10-18 04:31 UTC, merged