optmal license filter
kaiyuanshe/kaiyuanshe.github.io pull request #235
Opened 2023-10-22 08:45 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #234

2023-10-22 08:47 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4d8a1e17354848859bef92e7f1886a7d2b0a50b0/pages/tool/license-filter.tsx#L76-L78

chooseSteps[keyIndex] 报 `类型“string”的参数不能赋给类型“"正式成员" | "functions" | "主办单位" | "承办单位" | "协办单位" | "指导单位" | "大会合作单位" | "战略赞助" | "白金赞助" | "金牌赞助" | "银牌赞助" | "铜牌赞助" | "星牌赞助" | "特别支持" | "亮点赞助" | "成员赞助" | "讲师赞助" | "国际讲师差旅赞助" | "元宇宙会场赞助" | ... 178 more ... | "more_projects"”的参数。ts(2345)`  

我目前解决不了。 @TechQuery

2023-10-22 15:58 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4d8a1e17354848859bef92e7f1886a7d2b0a50b0/pages/tool/license-filter.tsx#L76-L78
> 
> chooseSteps[keyIndex] 报 `类型“string”的参数不能赋给类型“"正式成员" | "functions" | "主办单位" | "承办单位" | "协办单位" | "指导单位" | "大会合作单位" | "战略赞助" | "白金赞助" | "金牌赞助" | "银牌赞助" | "铜牌赞助" | "星牌赞助" | "特别支持" | "亮点赞助" | "成员赞助" | "讲师赞助" | "国际讲师差旅赞助" | "元宇宙会场赞助" | ... 178 more ... | "more_projects"”的参数。ts(2345)`  
> 
> 我目前解决不了。 @TechQuery 

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/4d8a1e17354848859bef92e7f1886a7d2b0a50b0/pages/tool/license-filter.tsx#L28-L39

改为以下形式

```ts
const chosenIndex = ['a', 'b'] as const;
```

2023-10-23 10:12 UTC, luojiyin1987 commented
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/96454dab-446d-4fe6-8e96-902ca85b49a0)
目前 界面里 `上一步` 跟别的按钮没区别度

2023-10-23 17:46 UTC, TechQuery commented
> ![image](https://user-images.githubusercontent.com/6524977/277303547-96454dab-446d-4fe6-8e96-902ca85b49a0.png) 目前 界面里 `上一步` 跟别的按钮没区别度

https://react-bootstrap.github.io/docs/components/buttons/

2023-10-23 17:55 UTC, TechQuery requested changes

2023-10-23 17:55 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +const chooseSteps = [
```suggestion
const choiceSteps = [
```
数据变/常量用名词性单词

2023-10-23 17:55 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +    console.log('stepindex keyIndex', stepIndex, keyIndex);
```suggestion
    console.table({ stepIndex, keyIndex });
```

2023-10-23 17:55 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +      stepIndex === 10
```suggestion
      stepIndex === chooseSteps.length
```

2023-10-23 17:55 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +      <h2>{t('filter_option') + ': ' + t(chooseSteps[keyIndex])}</h2>
```suggestion
      <h2>{t('filter_option')}: {t(chooseSteps[keyIndex])}</h2>
```

2023-10-23 17:55 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +        上一步
```suggestion
      <Button className="mb-2" onClick={backToLast}>
        上一步
```
并翻译文本

2023-10-23 17:55 UTC, TechQuery commented on translation/zh-CN.ts
> +    '您是否想选择强互惠(强传染)的协议？当您选择强互惠(强传染)许可证时，任何使用、修改或分发您的代码的人都必须遵循相同的许可证要求。这意味着他们必须提供源代码，并将其代码以相同的许可证发布。这样，您的代码的开放性将被保护，并且任何人都可以获得您的代码的源代码，以便进行学习、改进和共享。强互惠(强传染)许可证确保了对整个项目的开放性和共享性，促进了开源社区的合作和创新。但是，选择强互惠(强
中文用中文括号（下同）

2023-10-24 03:01 UTC, luojiyin1987 commented on pages/tool/license-filter.tsx
> +const chooseSteps = [
复数形式说明是数组

2023-10-24 08:37 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +const chooseSteps = [
> 复数形式说明是数组

我没说后面的复数，我说的是前面的单词啊

2023-10-24 09:11 UTC, luojiyin1987 commented
本来想也更新英文的相关说明文字，怕不严谨，还是交给熟悉英文的人来改。

2023-10-24 13:07 UTC, TechQuery commented
> 本来想也更新英文的相关说明文字，怕不严谨，还是交给熟悉英文的人来改。 

本来就是在过程当中锻炼各种技能的，还有人 review 嘛。

2023-10-24 13:10 UTC, TechQuery requested changes

2023-10-24 13:10 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +          {t('infectionRange')}:{judgeInfectionRange(feature.infectionRange)}
```suggestion
          {t('infectionRange')}: {judgeInfectionRange(feature.infectionRange)}
```

2023-10-24 13:10 UTC, TechQuery commented on pages/tool/license-filter.tsx
> +          {t('marketingEndorsement')}:{judge(feature.marketingEndorsement)}
```suggestion
          {t('marketingEndorsement')}: {judge(feature.marketingEndorsement)}
```

2023-10-24 13:10 UTC, TechQuery commented on translation/zh-CN.ts
> +  infectionIntensity: '互惠(传染)需求',
中文括号（下同）

2023-10-25 03:36 UTC, luojiyin1987 commented
英文部分 我已经尽自己最大努力改了一版。 需要别的人来 review 了。 
[相关资料](https://kaiyuanshe.feishu.cn/wiki/Wi4twa199iCW9MkjiJfcmE8cnMf?from=from_copylink)

2023-10-30 17:26 UTC, TechQuery approved these changes

2023-10-30 17:26 UTC, merged