feat: docker healtheck
kaiyuanshe/kaiyuanshe.github.io pull request #243
Opened 2023-10-24 02:29 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #242

2023-10-24 18:51 UTC, TechQuery requested changes

2023-10-24 18:51 UTC, TechQuery commented on docker-compose.yml
> +      test: node healthcheck.js
`curl` 不行吗？

2023-10-25 00:39 UTC, luojiyin1987 commented on docker-compose.yml
> +      test: node healthcheck.js
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/6a1fc6b9-55c0-4032-97ae-3868e475ab23)
用的应该  node18:slim 精简镜像， 里面没 curl 和 wget 命令。 只好调用里面肯定有的 Nodejs 运行环境。 或者在构建镜像的时候按照 curl。

2023-10-25 06:51 UTC, TechQuery commented on docker-compose.yml
> +      test: node healthcheck.js
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/6a1fc6b9-55c0-4032-97ae-3868e475ab23)
> 用的应该  node18:slim 精简镜像， 里面没 curl 和 wget 命令。 只好调用里面肯定有的 Nodejs 运行环境。 或者在构建镜像的时候按照 curl。

可以装一下 `curl`

2023-10-25 10:58 UTC, TechQuery requested changes

2023-10-25 10:58 UTC, TechQuery commented on Dockerfile
> +RUN apt-get install -y curl
```suggestion
RUN apt install -y curl
```

2023-10-25 10:58 UTC, TechQuery commented on docker-compose.yml
> +      test: ['CMD-SHELL', 'curl -f http://localhost:3000/ || exit 1']
```suggestion
      test: ['CMD-SHELL', 'curl -f http://localhost:3000/']
```

2023-10-25 13:03 UTC, luojiyin1987 commented on Dockerfile
> +RUN apt-get install -y curl
直接运行  `RUN apt install -y curl`  在构建镜像会报错退出 
`WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`

要完成先运行 `apt-get update `  否则会报错退出。 
所以完整的命令是
`RUN apt-get update && apt-get install  -y curl `

2023-10-25 13:17 UTC, luojiyin1987 commented on docker-compose.yml
> +      test: ['CMD-SHELL', 'curl -f http://localhost:3000/ || exit 1']
shell 报错退出的值是非 0 值，不一定是 1 。  Docker  能判断的是  0 (healthy)  1(unhealthy ), 别的值是理解不了的 。
[curl 的返回值](https://everything.curl.dev/usingcurl/returns) 
[so上相关讨论](https://stackoverflow.com/questions/72454346/docker-health-check-command-do-we-really-need-exit-1)

2023-10-25 13:27 UTC, luojiyin1987 commented
这个方案只能标记 Docker 为 unhealthy  状态，不能重启。
解决办法
1   运行  [autoheal容器](https://hub.docker.com/r/willfarrell/autoheal/) 
2    用自己熟悉的语言调用 Docker API ，定时检查。
3   定时 shell 脚本解决

[so相关讨论](https://stackoverflow.com/questions/47088261/restarting-an-unhealthy-docker-container-based-on-healthcheck)

2023-11-02 02:55 UTC, luojiyin1987 commented
[目前参考这个](https://blog.bitexpert.de/blog/autoheal-your-docker-containers)    由于网络原因，服务器拉不下镜像，还没测试通过。

2023-11-02 10:02 UTC, TechQuery requested changes

2023-11-02 10:02 UTC, TechQuery commented on Dockerfile
> +RUN apt-get update && apt-get install curl -y --no-install-recommends
```suggestion
RUN apt-get update && \
    apt-get install curl -y --no-install-recommends
```

2023-11-02 10:29 UTC, luojiyin1987 commented
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/6541af40-01ee-4001-af2f-abaf3a41558d)
已经验证可以重启 docker 容器

2023-11-02 10:48 UTC, luojiyin1987 commented
我把原来的
```yml
COPY package.json pnpm-lock.yaml .npmrc /home/node/app/
RUN pnpm i --frozen-lockfile

COPY . /home/node/app
RUN pnpm build
```
改为 
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d66ae75983885c6532eb299abd4aa932dc80f9ce/Dockerfile#L13-L15

2023-11-02 17:31 UTC, TechQuery commented
> 我把原来的
> 
> ```yaml
> COPY package.json pnpm-lock.yaml .npmrc /home/node/app/
> RUN pnpm i --frozen-lockfile
> 
> COPY . /home/node/app
> RUN pnpm build
> ```
> 
> 改为 @TechQuery
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d66ae75983885c6532eb299abd4aa932dc80f9ce/Dockerfile#L13-L15

不要这样，这样就没法利用 Docker 的**层状文件系统**缓存 `node_modules/` 了。

2023-11-02 17:32 UTC, TechQuery requested changes

2023-11-02 17:32 UTC, TechQuery commented on Dockerfile
> -COPY . /home/node/app
还原，因为：https://zhuanlan.zhihu.com/p/83793004

2023-11-03 02:21 UTC, luojiyin1987 commented
> > 我把原来的
> > ```yaml
> > COPY package.json pnpm-lock.yaml .npmrc /home/node/app/
> > RUN pnpm i --frozen-lockfile
> > 
> > COPY . /home/node/app
> > RUN pnpm build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 改为 @TechQuery
> > https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/d66ae75983885c6532eb299abd4aa932dc80f9ce/Dockerfile#L13-L15
> 
> 不要这样，这样就没法利用 Docker 的**层状文件系统**缓存 `node_modules/` 了。

已经改回去了

2023-11-03 02:49 UTC, luojiyin1987 commented
[nextjs 官方的 dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
多层构建

2023-11-03 09:44 UTC, TechQuery requested changes

2023-11-03 09:44 UTC, TechQuery commented on .dockerignore
> +README.md
```suggestion
docker-compose.yml
```
上面已经有了，但这个文件没忽略。

2023-11-03 09:44 UTC, TechQuery commented on Dockerfile
>  RUN pnpm prune --prod || true \
这里无需变更。

2023-11-03 09:48 UTC, TechQuery commented
> [nextjs 官方的 dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
> 多层构建
> 
> [相关讨论](https://github.com/vercel/next.js/discussions/16995)
> [相关文档](https://nextjs.org/docs/pages/building-your-application/deploying#docker-image)

开放黑客松那边好像是基于这个教程写的，我不知道能减少多少体积，你可以再新开一个 PR 试一下。

2023-11-03 13:47 UTC, luojiyin1987 commented
> > [nextjs 官方的 dockerfile](https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile)
> > 多层构建
> > [相关讨论](https://github.com/vercel/next.js/discussions/16995)
> > [相关文档](https://nextjs.org/docs/pages/building-your-application/deploying#docker-image)
> 
> 开放黑客松那边好像是基于这个教程写的，我不知道能减少多少体积，你可以再新开一个 PR 试一下。

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/8ea60a18-2d74-4d50-89d0-7a70f14445a0)
体积大小差别挺明显的， 不过会导致打包镜像时间变长。

2023-11-03 16:11 UTC, TechQuery approved these changes

2023-11-03 16:21 UTC, TechQuery approved these changes

2023-11-03 16:22 UTC, merged