fix: nav bar dropdown list title display
kaiyuanshe/kaiyuanshe.github.io pull request #249
Opened 2023-10-25 03:11 UTC by PapayaHUANG

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #248 

## Preview
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/c8d7002b-d961-4593-a37f-a9c147b088bc)

2023-10-25 06:53 UTC, wangrunlin requested changes

2023-10-25 06:56 UTC, TechQuery requested changes

2023-10-25 06:56 UTC, TechQuery commented on components/Layout/MainNav.tsx
> +        <Nav className="flex-fill ms-3 align-items-center ">
无需变更

2023-10-25 06:56 UTC, TechQuery commented on components/Layout/MainNav.tsx
>                    <NavDropdown.Item key={title} href={path}>
文字居中放 `Item` 上，容器用组件属性：https://react-bootstrap.github.io/docs/components/dropdowns/#drop-directions

2023-10-25 08:18 UTC, PapayaHUANG commented on components/Layout/MainNav.tsx
>                    <NavDropdown.Item key={title} href={path}>
`text-center`放到 `Item`解决的是下拉菜单打开了之后内部文字的居中，我个人审美是内部不需要居中会好看一些，和父菜单刚好形成了区分。
容器的组件属性没有可以解决现在这个 bug 的诶（我翻文档没有找到😢）
这个 bug 的 root-cause 是因为下拉菜单 title 没有定宽，下拉菜单打开之后宽度被撑开，title 就向左平移了，所以我用文字居中无视这个条件的改变。

所以我错过了文档哪里？（默默哭泣

2023-10-25 18:31 UTC, TechQuery commented on components/Layout/MainNav.tsx
>                    <NavDropdown.Item key={title} href={path}>
我折腾了一下，你看看我的更改。

2023-10-26 04:29 UTC, PapayaHUANG commented on components/Layout/MainNav.tsx
>                    <NavDropdown.Item key={title} href={path}>
你修改后子菜单就文字居中了啊，桌面端这样不是很好看吧🤔
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/183ebd34-5349-488b-81e7-6ff65559df16)
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/9f1af406-6d5b-4e8b-864b-d985ea4c10c4)

2023-10-26 04:30 UTC, PapayaHUANG commented on components/Layout/MainNav.tsx
>                <NavDropdown key={title} title={title} className="text-center">
这里的`text-center` 还是保留了吖

2023-10-26 10:58 UTC, TechQuery commented on components/Layout/MainNav.tsx
>                    <NavDropdown.Item key={title} href={path}>
> 你修改后子菜单就文字居中了啊，桌面端这样不是很好看吧🤔
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/183ebd34-5349-488b-81e7-6ff65559df16)
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/9f1af406-6d5b-4e8b-864b-d985ea4c10c4)

那就再加个 `text-md-start` 响应式类

2023-10-26 11:00 UTC, TechQuery commented on components/Layout/MainNav.tsx
>                <NavDropdown key={title} title={title} className="text-center">
> 这里的`text-center` 还是保留了吖

嗯，仔细试了一下，让菜单不摆动的居中方式，还要更上层的布局配合。

2023-10-27 08:01 UTC, TechQuery approved these changes

2023-10-27 13:44 UTC, wangrunlin approved these changes

2023-10-27 13:48 UTC, merged