fix: scroll agenda card's badge
kaiyuanshe/kaiyuanshe.github.io pull request #250
Opened 2023-10-25 06:50 UTC by zshnb

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #236

2023-10-25 22:05 UTC, TechQuery requested changes

2023-10-25 22:05 UTC, TechQuery commented on components/Base/TextScrollableBox/index.tsx
> +}
```suggestion
import { FC } from 'react';

import style from './style.module.less';

export const TextScrollableBox: FC = ({ children }) => (
    <div className={style.box}>
      <div className={style.scrollItem}>{children}</div>
    </div>
  );
```

2023-10-25 22:05 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +    min-width: 100%;
```suggestion
  white-space: nowrap;
  overflow: hidden;
  .scrollItem {
    display: inline-block;
    width: fit-content;
    min-width: 100%;
    animation: scroll linear 4s alternate infinite;
```

2023-10-25 22:05 UTC, TechQuery commented on pages/activity/[id]/index.module.less
>  }
用循环实现：https://lesscss.org/functions/#list-functions-each

2023-10-25 22:05 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +          <img className={styles.img} src={blobURLOf(activity.image)} />
```suggestion
          <img className={styles.img} loading="lazy" src={blobURLOf(activity.image)} />
```

2023-10-30 05:39 UTC, wangrunlin requested changes

2023-10-30 05:39 UTC, wangrunlin commented on .gitignore
> +.idea
```suggestion
.idea/
```

加上 `/` 可以让开发人员了解到这是一个文件夹

2023-10-30 05:39 UTC, wangrunlin commented on README.md
> +第三步，安装依赖并运行开发服务器:
这里为什么要修改为第三步？第二步呢？

2023-10-30 05:39 UTC, wangrunlin commented on components/Base/TextScrollableBox/index.tsx
> +export const TextScrollableBox: FC<TextScrollableBoxProps> = ({
```suggestion
};

export const TextScrollableBox: FC<TextScrollableBoxProps> = ({
```

2023-10-30 13:49 UTC, Five-great commented on pages/activity/[id]/index.module.less
> +@keyframes scroll {
```css
@keyframes scroll {
  0%,
  10% {
    margin-top: 0;
    transform: translateY(0);
  }

  90%,
  100% {
    margin-top: var(--wrapHeight);
    transform: translateY(-100%);
  }
}
```
css3 局部变量  `--wrapHeight` 设置外部容器高度

2023-10-30 21:40 UTC, TechQuery requested changes

2023-10-30 21:40 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +                <TextScrollableBox duration={'20s'}>{title}</TextScrollableBox>
```suggestion
                <TextScrollableBox duration="20s">{title}</TextScrollableBox>
```

2023-10-30 21:40 UTC, TechQuery commented on components/Base/TextScrollableBox/index.tsx
> +};
```suggestion
import { FC, PropsWithChildren } from 'react';

import style from './style.module.less';

export type TextScrollableBoxProps = PropsWithChildren<{
  width?: number;
  duration?: string;
}>;
```

2023-10-30 21:40 UTC, TechQuery commented on components/Base/TextScrollableBox/index.tsx
> +};
```suggestion
export const TextScrollableBox: FC<TextScrollableBoxProps> = ({
  children,
  width,
  duration,
}) => (
    <div className={style.box} style={{ width, '--duration': duration }>
      <div className={style.scrollWrap}>
        <div className={style.scrollItem}>{children}</div>
      </div>
    </div>
  );
```

2023-10-30 21:40 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +  }
可用 CSS 工具类代替：`mw-100 d-inline-block align-top overflow-hidden text-nowrap`

参考：https://getbootstrap.com/docs/5.3/utilities/sizing/

2023-10-30 21:40 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +              loading={'lazy'}
```suggestion
              loading="lazy"
```

2023-10-31 03:04 UTC, zshnb commented on pages/activity/[id]/index.module.less
> +@keyframes scroll {
外部要怎么使用这个参数呢

2023-10-31 04:22 UTC, Five-great commented on pages/activity/[id]/index.module.less
> +@keyframes scroll {
和文字那个一样嘛

2023-10-31 04:36 UTC, Five-great commented on pages/activity/[id]/index.module.less
> +  .scrollWrap {
```css
.scrollWrap {
   --duration: 20s;
    max-height: 100%;
    animation: scrollWrap linear var(--duration) alternate infinite;
    display: inline-block;
    font-size: 0;
    .scrollItem {
      display: inline-block;
      animation: scrollItem linear var(--duration) alternate infinite;
    }
  }
}
@keyframes scrollItem {
  0%,
  10% {
    transform: translateY(0);
  }

  90%,
  100% {
    transform: translateY(-100%);
  }
}

@keyframes scrollWrap {
  0%,
  10% {
    transform: translateY(0);
  }

  90%,
  100% {
    transform: translateY(100%);
  }
}
```  
用这个 在一个dom 上处理 会有问题  采用 双层反向滚动 处理更好  同步 `--duration` 就好了

2023-10-31 04:46 UTC, Five-great commented on pages/activity/[id]/index.tsx
> +              loading={'lazy'}
最好还是抽成 超长自动滚动组件

2023-11-01 13:42 UTC, Five-great commented on components/Base/ImageScrollableBox/index.module.less
> +.scrollWrap {
```less
.scrollWrap {
  --duration: 10s;
  animation: scrollWrap linear var(--duration) alternate infinite;
  font-size: 0;
  &:hover {
      animation-play-state: paused;
     .scrollItem{
         animation-play-state: paused;
      }
  }
  .scrollItem {
    animation: scrollItem linear var(--duration) alternate infinite;
  }
}
```

2023-11-01 13:45 UTC, Five-great commented on components/Base/ImageScrollableBox/index.tsx
> +    <div className={`d-inline-block mh-100 ${styles.scrollWrap}`}>
```html
  <div className={`d-inline-block mh-100 ${styles.scrollWrap}`}>
      <div className={`d-inline-block ${styles.scrollItem}`}>
        {children}
      </div>
    </div>
```
最好像文本滚动一样 更具灵活性

2023-11-02 17:29 UTC, TechQuery requested changes

2023-11-02 17:29 UTC, TechQuery commented on components/Base/ImageScrollableBox/index.tsx
> +};
```suggestion
import { Image, ImageProps } from 'react-bootstrap';

import styles from './index.module.less';

export interface ImageScrollableBoxProps extends ImageProps {
  duration?: string;
}

export const ImageScrollableBox: FC<ImageScrollableBoxProps> = ({
  src,
  loading = 'lazy',
  duration,
  ...props,
}) => (
    <div
      className={`d-inline-block mh-100 ${styles.scrollWrap}`}
      // @ts-ignore
      style={{ '--duration': duration }}
    >
      <Image
        className={`d-inline-block ${styles.scrollItem}`}
        {...{ ...props, src, loading }}
      />
    </div>
  );
```

2023-11-02 17:29 UTC, TechQuery commented on components/Base/TextScrollableBox/index.tsx
> +}
```suggestion
}) => (
    // @ts-ignore
    <div className={style.box} style={{ width, '--duration': duration }}>
      <div
        className="d-inline-block align-top overflow-hidden text-nowrap mw-100"
      >
        <div className={`d-inline-block float-start ${style.scrollItem}`}>
          {children}
        </div>
      </div>
    </div>
  );
```

2023-11-03 12:36 UTC, TechQuery requested changes

2023-11-03 12:36 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +              src={activity.image as string}
```suggestion
              src={blobURLOf(activity.image)}
```

2023-11-03 13:57 UTC, Five-great commented on pages/activity/[id]/index.tsx
> +              loading="lazy"
页面banner 一来就加载了 无需 loading="lazy 徒增性能和损失体验

2023-11-03 14:02 UTC, Five-great commented on components/Base/VerticalScrollableBox/index.tsx
> +  children,
最好可以 设定 宽高，虽然目前用不上

2023-11-03 15:01 UTC, zshnb commented on components/Base/VerticalScrollableBox/index.tsx
> +  children,
先不加了，用上了再加吧

2023-11-03 16:13 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +              loading="lazy"
> 页面banner 一来就加载了 无需 loading="lazy 徒增性能和损失体验

如果是滚动到下面再刷新后再滚回去呢？

2023-11-04 06:57 UTC, TechQuery approved these changes

2023-11-04 14:29 UTC, wangrunlin approved these changes

2023-11-04 14:32 UTC, merged

2023-11-04 14:54 UTC, Five-great reviewed
ok