feat: show location and url on agenda calendar
kaiyuanshe/kaiyuanshe.github.io pull request #251
Opened 2023-10-26 07:13 UTC by PapayaHUANG

- [x] Labels
- [ ] Assignees
- [x] Reviewers

Closes #247 

## Preview
<img width="262" alt="image" src="https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/70144378/429ac587-54d9-454a-a36c-5edd46497374">

2023-10-26 11:08 UTC, TechQuery requested changes

2023-10-26 11:08 UTC, TechQuery commented on models/Activity/Forum.ts
> +      location: location && normalizeTextArray(location as TableCellText[]),
该字段也是关联关系类型，不是通过查找引用或公式生成的文本字段。

2023-10-26 11:08 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> -          location={location + ''}
议程可以选独立的教室，但没有时要继承分论坛的教室，还需要整个活动的总地址。

2023-10-27 04:25 UTC, PapayaHUANG commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> -          location={location + ''}
> 还需要整个活动的总地址
我看了一下多维表格里面 Place 这个表有具体的地址（`location`字段），不过地址的数据类型是 `int`，就是具体的坐标，我不知道怎么在取数据的时候把它转换成文字。
我们用的 `react-icalendar-link` 对 `location` 的参数要求是 `string` https://github.com/josephj/react-icalendar-link/blob/master/src/utils.ts#L6C21-L6C21
难道用笨办法，就是 hard code 地址然后和取到的具体教室拼接🤔

> 议程可以选独立的教室，但没有时要继承分论坛的教室
原始代码取的 `location` 字段是 `Forum` 这个表格里的，我修改后是直接取 `agenda` 这个表格里的 `location` 字段，这两个字段在多维表格里设置的双向关联条件是一样的，所以理论上来说取出来的值应该是一样的。
所以取出来的教室就是论坛教室吧？我想到时候如果没有教室的话，就直接显示总活动地址？那么就回到第一个问题。

2023-10-27 07:54 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> -          location={location + ''}
> 多维表格里面 Place 这个表有具体的地址（location字段），不过地址的数据类型是 int，就是具体的坐标，我不知道怎么在取数据的时候把它转换成文字。

它是个对象，里面有地址文本字段。

2023-10-27 08:00 UTC, TechQuery commented on pages/activity/[id]/agenda/[agendaId]/index.tsx
> -          location={location + ''}
> 原始代码取的 location 字段是 Forum 这个表格里的，我修改后是直接取 agenda 这个表格里的 location 字段，这两个字段在多维表格里设置的双向关联条件是一样的，所以理论上来说取出来的值应该是一样的。

双向关联指的是当前表的当前字段和引用表之间的直接关系，不是当前表的另一个关联字段和引用表的关系。如果真有关系，此处会直接显示关联出来的内容，而不是为空。

2023-12-21 17:26 UTC, merged