fix: TextScrollableBox
kaiyuanshe/kaiyuanshe.github.io pull request #268
Opened 2023-11-06 15:21 UTC by zshnb

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2023-11-06 17:03 UTC, TechQuery requested changes

2023-11-06 17:03 UTC, TechQuery commented on components/Activity/Agenda/Card.tsx
> +              <TextScrollableBox width="80px">{type + ''}</TextScrollableBox>
用像素值写死会影响**响应式适配**，尽量用**相对值**。

2023-11-06 17:03 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +  width: var(--width);
为什么不直接设置这个属性，而用自定义属性？感觉多次一举……

2023-11-06 17:03 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +      animation: scroll linear var(--duration) alternate infinite;
直接设置具体属性就好了：https://developer.mozilla.org/en-US/docs/Web/CSS/animation-duration

2023-11-07 02:56 UTC, zshnb commented on components/Base/TextScrollableBox/style.module.less
> +      animation: scroll linear var(--duration) alternate infinite;
那其他几个都要设置具体属性吗？

2023-11-07 02:56 UTC, zshnb commented on components/Base/TextScrollableBox/style.module.less
> +  width: var(--width);
因为用的地方可以指定宽度

2023-11-08 04:33 UTC, zshnb commented on components/Base/TextScrollableBox/style.module.less
> +      animation: scroll linear var(--duration) alternate infinite;
为啥要拆开设置属性，有什么好处吗

2023-11-08 10:58 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +      animation: scroll linear var(--duration) alternate infinite;
> 为啥要拆开设置属性，有什么好处吗

直接设置原生的 CSS 属性会更方便，而自定义属性主要用于没有单独的 CSS 属性，特别是需要通过计算获得的。

2023-11-13 11:04 UTC, TechQuery requested changes

2023-11-13 11:04 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +              style={{ maxWidth: '100%' }}
```suggestion
              className="mw-100"
```

2023-11-13 11:04 UTC, TechQuery commented on pages/activity/[id]/index.tsx
> +            className={'d-sm-block'}
```suggestion
            className="d-sm-block"
```

2023-11-13 13:19 UTC, Five-great commented on components/Activity/Agenda/Card.tsx
> +              <TextScrollableBox width="80px">{type + ''}</TextScrollableBox>
最好不要写width 用max-width

2023-11-16 14:09 UTC, Five-great commented on components/Activity/Agenda/Card.tsx
> +              <TextScrollableBox width="80px">{type + ''}</TextScrollableBox>
```suggestion
              <TextScrollableBox maxWidth="80px">{type + ''}</TextScrollableBox>
```

2023-11-16 14:10 UTC, Five-great commented on components/Activity/Agenda/Card.tsx
> +                <TextScrollableBox duration="20s" width="330px">
```suggestion
                <TextScrollableBox duration="20s" maxWidth="330px">
```

2023-11-16 15:11 UTC, TechQuery requested changes

2023-11-16 15:11 UTC, TechQuery commented on components/Base/TextScrollableBox/index.tsx
> +    <TextScrollable maxWidth={maxWidth} duration={duration} height={height}>
```suggestion
    <TextScrollable {...{ maxWidth, duration, height }}>
```

2023-11-16 15:11 UTC, TechQuery commented on components/Base/TextScrollableBox/style.module.less
> +    .scrollItem{
格式化脚本没执行成功

2023-11-28 03:44 UTC, TechQuery approved these changes

2023-11-28 03:45 UTC, merged