Option docker image size
kaiyuanshe/kaiyuanshe.github.io pull request #270
Opened 2023-11-10 08:48 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #269

2023-11-10 09:57 UTC, luojiyin1987 commented
https://github.com/pnpm/pnpm/issues/6100 
pnpm  没有实现  `npm ci` 的功能
```shell
pnpm ci
ERR_PNPM_CI_NOT_IMPLEMENTED  The ci command is not implemented yet
```

2023-11-11 03:34 UTC, luojiyin1987 commented
[pnpm  的dockerfile ](https://pnpm.io/docker)

改动比较大，我无法在我的服务器上进行测试。  只是用pnpm 创建的了一个 nextjs 14 的示范项目进行测试。
@TechQuery

2023-11-11 12:49 UTC, TechQuery requested changes

2023-11-11 12:49 UTC, TechQuery commented on Dockerfile
> +COPY . /app
安装依赖前先复制依赖配置文件，让安装那一步可以复用缓存，构建前再复制所有文件。

2023-11-11 12:49 UTC, TechQuery commented on Dockerfile
> +RUN pnpm run build
```suggestion
RUN pnpm build
```

2023-11-11 12:49 UTC, TechQuery commented on Dockerfile
> +CMD [ "pnpm", "start" ]
此处不用改

2023-11-12 04:49 UTC, luojiyin1987 commented on Dockerfile
> +COPY . /app
在别的地方改动，有很多意外的问题。如 public 文件夹没复制成功。  要很多魔改，可维护性差。 还要继续尝试

2023-11-12 07:50 UTC, luojiyin1987 commented on Dockerfile
> +COPY . /app
[buildkit](https://yeasy.gitbook.io/docker_practice/buildx/buildkit)  已经解决这个问题 
如 pnpm 官方说的  `It is impossible to create reflinks or hardlinks between a Docker container and the host filesystem during build time. The next best thing you can do is using BuildKit cache mount to share cache between builds. `

2023-11-27 14:14 UTC, luojiyin1987 commented
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/397f6532-e87c-4f14-981d-944e5a4fc768)

![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/5dab9d10-90c7-47a0-9c12-5fc75e45c253)
相对线上的就节省了 100M 空间 

`RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile  --ignore-scripts`  加了 `--ignore-script` 。 避免在运行安装生产环境依赖前， 运行 "prepare": "husky install" 。 导致报错 `husky: not found`  。 退出 docker  镜像的构建。  

npmrc 相关配置已经测试过了， CI 过程中不会出问题。

2023-11-27 14:34 UTC, TechQuery commented
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/397f6532-e87c-4f14-981d-944e5a4fc768)
> 
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/5dab9d10-90c7-47a0-9c12-5fc75e45c253)
> 相对线上的就节省了 100M 空间 

我用同脚手架的项目测试，能省一半以上的空间。

2023-11-27 14:38 UTC, TechQuery requested changes

2023-11-27 14:38 UTC, TechQuery commented on Dockerfile
> +RUN rm .npmrc
```suggestion
```
此处没必要，你删了之所以没问题是因为它目前里面的配置是在安装时起作用，运行时没有用。

2023-11-27 14:38 UTC, TechQuery commented on Dockerfile
> +CMD [ "npm", "start" ]
```suggestion
CMD ["npm", "start"]
```
没必要改动，我们遵循**最小变更**原则。

2023-11-27 14:47 UTC, merged