Fix ：department query error
kaiyuanshe/kaiyuanshe.github.io pull request #275
Opened 2023-11-28 11:57 UTC by huoyueyuyuan

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #274

2023-11-28 12:51 UTC, TechQuery reviewed
继续在本 PR 开发部门详情页。

2023-11-28 15:24 UTC, TechQuery requested changes

2023-11-28 16:46 UTC, TechQuery requested changes

2023-11-28 16:46 UTC, TechQuery commented on pages/department/[name].tsx
> +          </Col>
```suggestion
          {summary && (
              <Col
                xs={12}
                sm={8}
                as="article"
                dangerouslySetInnerHTML={{
                  __html: marked(summary as string),
                }}
              />
            )}
```

2023-11-28 16:46 UTC, TechQuery commented on pages/department/[name].tsx
> +    const { department } = this.props;
```suggestion
    const { department } = this.props;
    const { name, summary } = department;
```

2023-11-28 16:46 UTC, TechQuery commented on pages/department/[name].tsx
> +            {this.renderProfile(department)}
直接引用现成组件：

https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/fb626be0c01b92873f7d14b5e11cffb7212513f0/components/Department/Card.tsx#L13-L50

2023-11-29 00:14 UTC, huoyueyuyuan commented on pages/department/[name].tsx
> +            {this.renderProfile(department)}
说到这个我发现自己漏做了。
搜索结果的战术，就是用GroupCard 。 因为要跳转到 部门详情页，所以 GroupCard  在标题加了  链接。 --- 这个就是昨天上午沟通的。
那么详情页这里，也直接引用 GroupCard 吗？

2023-11-29 00:54 UTC, huoyueyuyuan commented on pages/department/[name].tsx
> +            {this.renderProfile(department)}
![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/393c4cdd-e0db-4314-91c8-a6afce29b38b)
GroupCard 这里的改动，组织架构这里的预览，也影响了

2023-11-29 01:20 UTC, TechQuery commented on pages/department/[name].tsx
> +            {this.renderProfile(department)}
> ![image](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/22514503/393c4cdd-e0db-4314-91c8-a6afce29b38b)
> GroupCard 这里的改动，组织架构这里的预览，也影响了

把链接的下划线样式去掉就行了，其它不影响。

2023-11-29 15:04 UTC, TechQuery requested changes

2023-11-29 15:04 UTC, TechQuery commented on components/Department/Card.tsx
> +    </a>
1. 链接在里面
2. 基本类型用小写

2023-11-29 15:04 UTC, TechQuery commented on pages/department/[name].tsx
> +        <CommentBox category="General" categoryId="DIC_kwDOB88JLM4COLSV" />
部门卡片放左边，成员头像放右边。

2023-12-01 00:53 UTC, huoyueyuyuan commented on pages/department/[name].tsx
> +            {person.summary && (
@d-ethan3  他要接着写这PR ，让我休息下。
所以 就搭了框子 推上来。

2023-12-07 13:41 UTC, TechQuery requested changes

2023-12-07 13:41 UTC, TechQuery commented on pages/department/[name].tsx
> +    props: JSON.parse(JSON.stringify({ department, person, personnels })),
```suggestion
  { department: Department; personnels: Personnel[] }
>(errorLogger, translator(i18n), async ({ params: { name } = {} }) => {
  const [department] = await new DepartmentModel().getList({ name });

  if (!department) return { notFound: true, props: {} };

  const personnels = await new PersonnelModel().getList({
    department: name,
  });

  return {
    props: JSON.parse(JSON.stringify({ department, personnels })),
```

2023-12-07 13:41 UTC, TechQuery commented on pages/department/[name].tsx
> +            )}
```suggestion
```

2023-12-07 13:41 UTC, TechQuery commented on pages/department/[name].tsx
> +      </details>
这个页面不需要展示部门的认知履历，而是这个部门的所有人，即 `Personnel['recipient']` 字段。

2023-12-07 20:38 UTC, TechQuery requested changes
部门成员布局、组件参考 https://kaiyuanshe.cn/member 中某一组内的代码。

2023-12-07 20:38 UTC, TechQuery commented on pages/department/[name].tsx
> +      <LarkImage className="card-img-top rounded-0 " src={recipientAvatar} />
```suggestion
      <LarkImage className="card-img-top rounded-0" src={recipientAvatar} />
```

2023-12-08 13:03 UTC, TechQuery requested changes

2023-12-08 13:03 UTC, TechQuery commented on pages/department/[name].tsx
> +      <p>{recipient as string}</p>
```suggestion
      <div>{recipient as string}</div>
```
一个名字不是段落

2023-12-08 13:03 UTC, TechQuery commented on pages/department/[name].tsx
> +            <h2>{name as string}成员</h2>
```suggestion
            <h2>{name as string}成员</h2>
```
翻译一下

2023-12-09 15:24 UTC, TechQuery requested changes

2023-12-09 15:24 UTC, TechQuery commented on pages/department/[name].tsx
> +        className="overflow-hidden rounded-circle position-relative"
```suggestion
      className="d-flex flex-column align-items-center gap-2"
    >
      <LarkImage
        className="rounded-circle"
```

2023-12-09 15:24 UTC, TechQuery commented on pages/department/[name].tsx
> +    return (
```suggestion
    const { t } = i18n;

    return (
```

2023-12-09 15:24 UTC, TechQuery commented on pages/department/[name].tsx
> +export default class DepartmentDetailPage extends PureComponent<
```suggestion
import { observer } from 'mobx-react';

@observer
export default class DepartmentDetailPage extends PureComponent<
```
国际化文本的更新需要组件重绘，因此需要变为**数据观察者**。

2023-12-10 11:32 UTC, TechQuery requested changes

2023-12-10 11:32 UTC, TechQuery commented on .npmrc
这个文件不能删，是不要把你自己的登录配置提交上来……

2023-12-10 11:32 UTC, TechQuery commented on pnpm-lock.yaml
> +  autoInstallPeers: ture
`.npmrc` 文件恢复后重装，此处就没有变化了。

2023-12-10 12:54 UTC, TechQuery requested changes

2023-12-10 12:54 UTC, TechQuery commented on .npmrc
> +auto-install-peers = false
```suggestion
auto-install-peers = false

```
这个文件需要末尾行，否则 CI 会写坏文件：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/94d3427e0544b5970190de85520d4546862a7c05/.github/workflows/deploy-production.yml#L31-L35

2023-12-10 14:25 UTC, TechQuery approved these changes

2023-12-10 14:25 UTC, merged