feat: use libjemalloc
kaiyuanshe/kaiyuanshe.github.io pull request #289
Opened 2023-12-31 15:18 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #288

2023-12-31 17:02 UTC, TechQuery requested changes

2023-12-31 17:02 UTC, TechQuery commented on Dockerfile
> +ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
```suggestion
    apt-get install libjemalloc-dev ca-certificates curl -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# set environment variable to preload JEMalloc
ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"
```

2024-01-01 03:01 UTC, luojiyin1987 commented
![img_v3_026m_c7d107e5-25ed-4a07-a72e-f3277310745g](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/cccee3a7-1ed6-4d08-9fe9-4bbb6e3027d6)

![vIo4UaNnqy](https://github.com/kaiyuanshe/kaiyuanshe.github.io/assets/6524977/2fedd801-6075-4ffb-8285-125e92f8c273)
验证过程

2024-01-01 09:26 UTC, TechQuery approved these changes

2024-01-01 09:27 UTC, merged