[fix]Fixed internal honor data duplication issue
kaiyuanshe/kaiyuanshe.github.io pull request #297
Opened 2024-01-27 09:00 UTC by ziwu7

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #XXXXX

2024-01-28 14:47 UTC, TechQuery requested changes

2024-01-28 14:47 UTC, TechQuery commented on pages/community/award/[name].tsx
> +      }, [
本地格式化没执行

2024-01-28 14:47 UTC, TechQuery commented on pages/community/award/[name].tsx
> +     }
```suggestion
import 'array-unique-proposal';

     for (const year in group)
       group[year] = group[year].uniqueBy("recipient");
```
https://github.com/tc39/proposal-array-unique

2024-01-28 14:47 UTC, TechQuery commented on pages/community/honor/[name].tsx
删除旧文件

2024-01-30 09:31 UTC, ziwu7 commented on pages/community/award/[name].tsx
> +      }, [
已按要求修正

2024-01-30 09:32 UTC, ziwu7 commented on pages/community/award/[name].tsx
> +     }
已按要求修正

2024-01-30 09:32 UTC, ziwu7 commented on pages/community/honor/[name].tsx
已按要求修正

2024-01-30 11:46 UTC, TechQuery requested changes

2024-01-30 15:01 UTC, TechQuery requested changes

2024-01-30 15:01 UTC, TechQuery commented on pages/community/award/[name].tsx
>      return { props: JSON.parse(JSON.stringify({ group })) };
```suggestion
        .uniqueBy('recipient');

    return { props: JSON.parse(JSON.stringify({ group })) };
```

2024-01-30 15:03 UTC, TechQuery requested changes

2024-01-30 15:03 UTC, TechQuery commented on pages/community/award/[name].tsx
>      return { props: JSON.parse(JSON.stringify({ group })) };
```suggestion
    const group = await new PersonnelModel().getYearGroup(
      { award },
      ['createdAt'],
    );
    for (const year in group)
      group[year] = group[year]
        .filter(({ recipient }) => recipient)
        .uniqueBy('recipient');

    return { props: JSON.parse(JSON.stringify({ group })) };
```

2024-01-30 15:35 UTC, TechQuery approved these changes

2024-01-30 15:39 UTC, merged