Update en-US.ts
kaiyuanshe/kaiyuanshe.github.io pull request #310
Opened 2024-03-30 07:22 UTC by tedliu1

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2024-03-30 09:27 UTC, TechQuery requested changes
请先改完再合并。

2024-03-30 09:27 UTC, TechQuery commented on translation/en-US.ts
> +  community_structure: 'Organization Structure',
除非是长文本，否则左边的英文键名要和右边的英文翻译一致（除了大小写和空格），因此需要在整个项目中查找替换键名，可在此在线环境中操作：https://gitpod.io#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/310

2024-04-01 04:54 UTC, TechQuery requested changes
流水线构建失败的原因找到了。

2024-04-01 04:54 UTC, TechQuery commented on pages/department/index.tsx
> +    <h1>{t('organization_structure-chart')}</h1>
```suggestion
    <h1>{t('organization_structure_chart')}</h1>
```

2024-04-01 04:54 UTC, TechQuery commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
```suggestion
```
左边的键名在不加引号的时候遵循“标识符”规则，不能有减号。改为下划线后与上面另一条同名，因此删掉，同时其它语言对应条目也需要删掉。

2024-04-01 14:31 UTC, tedliu1 commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
1. 检查过滤，减号都已改为下划线。
2. 没理解 organization_structure_chart 与上面另一条同名。请问与哪一条同名？我没找到。

2024-04-01 14:33 UTC, TechQuery commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
> 没理解 organization_structure_chart 与上面另一条同名。请问与哪一条同名？我没找到。

选中键名后按 <kbd>Ctrl</kbd> + <kbd>F</kbd> 在文件内查找。

2024-04-01 14:42 UTC, tedliu1 commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
我用了周日例会里所说的方式已经修改了多数的英文拼写问题。刚刚也从头到尾检查了一遍，没有发现哪一条是重复的。你能具体说出行数吗？例如 60 行和哪一条重复了？

2024-04-01 14:51 UTC, TechQuery commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
> 你能具体说出行数吗？例如 60 行和哪一条重复了？

第 27 行

2024-04-01 14:58 UTC, tedliu1 commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
谢谢。哪我将 27 行及其它语言的 27 条相应的条目也删除，对吗？

2024-04-01 16:15 UTC, TechQuery commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
> 谢谢。哪我将 27 行及其它语言的 27 条相应的条目也删除，对吗？

具体保留哪种翻译由作为译者的您来确定，我只跟你讲清楚程序代码上有键名的唯一性。

2024-04-02 05:50 UTC, tedliu1 commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
更新完了，请审核。删除了 60 行重复的 organization_structure_chart。看看是否正确？

2024-04-02 09:57 UTC, TechQuery commented on translation/en-US.ts
> +  organization_structure-chart: 'Organization Structure Chart',
> 更新完了，请审核。删除了 60 行重复的 organization_structure_chart。看看是否正确？

还有一处重复和一处键名错误，我帮你改了：https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/310/commits/d73eaccbd72e7d3fc1e415fc3ad3363c0c817db6

2024-04-02 09:58 UTC, TechQuery approved these changes

2024-04-02 12:27 UTC, merged