[optimize]member page by year
kaiyuanshe/kaiyuanshe.github.io pull request #313
Opened 2024-06-10 14:58 UTC by ziwu7

[fix]Updated dependency: mobx-restful-table 2.0.0-rc.1

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #296

2024-06-10 15:19 UTC, TechQuery requested changes

2024-06-10 15:19 UTC, TechQuery commented on pages/department/[name].tsx
> +import { log } from 'console';
```suggestion
```
用原生的日志方法，不需要引入。

2024-06-10 15:19 UTC, TechQuery commented on pages/department/[name].tsx
>    });
```suggestion
```
没用的可以删。

2024-06-10 15:19 UTC, TechQuery commented on package.json
> +    "mobx-restful-table": "2.0.0-rc.1",
```suggestion
    "mobx-restful-table": "^2.0.0-rc.1",
```

2024-06-11 01:12 UTC, ziwu7 commented on pages/department/[name].tsx
> +import { log } from 'console';
已删除。

2024-06-11 01:13 UTC, ziwu7 commented on pages/department/[name].tsx
>    });
已将多余代码删除。

2024-06-11 01:13 UTC, ziwu7 commented on package.json
> +    "mobx-restful-table": "2.0.0-rc.1",
已修正。

2024-06-11 07:36 UTC, TechQuery commented
改一下组织结构图节点的链接指向

2024-06-11 07:52 UTC, TechQuery submitted a review, later dismissed

2024-06-11 17:51 UTC, merged