成员看板
kaiyuanshe/kaiyuanshe.github.io pull request #347
Opened 2024-10-23 14:46 UTC by luojiyin1987

[![PR-347](https://badgen.net/badge/GitHub.dev/PR-347/blue?icon=visualstudio)](https://github.dev/kaiyuanshe/kaiyuanshe.github.io/pull/347) [![PR-347](https://badgen.net/badge/GitHub%20codespaces/PR-347/black?icon=github)](https://codespaces.new/kaiyuanshe/kaiyuanshe.github.io/pull/347) [![PR-347](https://badgen.net/badge/GitPod.io/PR-347/orange?icon=git)](https://gitpod.io/?autostart=true#https://github.com/kaiyuanshe/kaiyuanshe.github.io/pull/347) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=kaiyuanshe&utm_campaign=badge_info)

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #314

2024-10-24 07:32 UTC, TechQuery commented
> 除了从  member 查询出有用的的信息，其他的如 department， meeting 等，并没有查询出有用的信息。我的查询是否有正确？  @TechQuery 

不同的人搜出的内容多寡不同，尽量用理事会的人来做测试，因为涉及的信息会比较全。

2024-10-24 07:35 UTC, TechQuery requested changes

2024-10-24 07:35 UTC, TechQuery commented on pages/member/[name].tsx
> +      }),
此处查出来的数据最终渲染到界面上会用不同的组件来实现，是一个明确的有限集合，建议直接硬编码每个 model，这样方便推导数据类型。

2024-10-24 09:50 UTC, TechQuery requested changes

2024-10-24 09:50 UTC, TechQuery commented on pages/member/[name].tsx
> +  [key: string]: any;
类型要么硬编码，要么从别的硬编码基础类型上推导出来。

2024-10-24 09:50 UTC, TechQuery commented on pages/member/[name].tsx
> +] as const;
说的硬编码是直接 `new 具体Model()`

2024-10-25 07:57 UTC, TechQuery requested changes

2024-10-25 07:57 UTC, TechQuery commented on pages/member/[name].tsx
> +      new systemStore.searchMap.NGO().getSearchList(name + '')
可以直接 new import 进来的具体 Search 类，不用这么长的查找链。

2024-10-25 07:57 UTC, TechQuery commented on pages/member/[name].tsx
> +        }),
尽量把过长的对象自变量放在上面声明常量，尽可能写成一行，然后下面引用。

2024-10-25 07:57 UTC, TechQuery commented on pages/member/[name].tsx
> +      personnels,
没执行格式化

2024-10-25 15:02 UTC, luojiyin1987 commented on pages/member/[name].tsx
> +      personnels,
编译时间太长了

2024-10-26 08:12 UTC, luojiyin1987 commented
好几个 render 挺相似的， 是否要抽象到同一个 render 里 ？ @TechQuery   

如果页面结构没问题， 我准备做国际化。

2024-10-26 08:19 UTC, TechQuery requested changes

2024-10-26 08:26 UTC, TechQuery commented
> 好几个 render 挺相似的， 是否要抽象到同一个 render 里 ？ @TechQuery

只有每一节的标题和外框是重复的，内部各类数据结构的卡片组件都不同：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/bca858901a21c7e2704af9ccfbf4aa4f82c23ab8/pages/department/%5Bname%5D/%5Byear%5D.tsx#L98-L106

2024-10-26 15:13 UTC, luojiyin1987 commented
> > 好几个 render 挺相似的， 是否要抽象到同一个 render 里 ？ @TechQuery
> 
> 只有每一节的标题和外框是重复的，内部各类数据结构的卡片组件都不同：
> 
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/bca858901a21c7e2704af9ccfbf4aa4f82c23ab8/pages/department/%5Bname%5D/%5Byear%5D.tsx#L98-L106

要改什么？ 不是根据类型定义来写 ？

2024-10-26 16:05 UTC, TechQuery commented
> 要改什么？ 不是根据类型定义来写 ？ 

是啊，我说的是 —— 各种可搜索的数据类型都写好了 `<XXXCard />` 组件，直接引用、传数据即可。

2024-10-31 13:32 UTC, TechQuery requested changes

2024-10-31 13:32 UTC, TechQuery commented on pages/member/[name].tsx
> +    </section>
```suggestion
      <details className="mb-3">
        <summary>{t('related_articles')}</summary>
          <Row as="ol" className="list-unstyled g-3" xs={1} md={2}>
            {articles.map(article => (
              <Col key={article.id as string} as="li">
                <ArticleCard {...article} />
              </Col>
            ))}
          </Row>
      </details>
```

2024-10-31 13:32 UTC, TechQuery commented on pages/member/[name].tsx
> +        <summary>{t('related_department')}</summary>
```suggestion
        <summary>{textJoin(t('related'), t('department'))}</summary>
```
这样只需新加一个词，其它均可复用。

2024-10-31 13:32 UTC, TechQuery commented on pages/member/[name].tsx
> +            <li key={meeting.id as string}>{meeting.name as string}</li>
这两个都有卡片组件。

2024-11-05 05:08 UTC, TechQuery approved these changes

2024-11-05 05:09 UTC, merged