意见箱 功能
kaiyuanshe/kaiyuanshe.github.io pull request #368
Opened 2024-11-17 15:22 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #329

2024-11-17 16:41 UTC, TechQuery requested changes

2024-11-17 16:41 UTC, TechQuery commented on models/Governance/Issue.ts
> +}
这些函数名都是上面的类定义的方法，写到上面的 `class` 中去。

2024-11-18 03:35 UTC, luojiyin1987 commented
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b3a530f80d637d7fb44e9937e5ebdae603d2ed03/models/Governance/Issue.ts#L68-L71
department proposals meeting 都是有数据关联的，  不知道这样写是否正确 ？  @TechQuery

2024-11-18 10:56 UTC, TechQuery commented
> https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/b3a530f80d637d7fb44e9937e5ebdae603d2ed03/models/Governance/Issue.ts#L68-L71
> department proposals meeting 都是有数据关联的，  不知道这样写是否正确 ？  @TechQuery 

不正确的话首先类型推断或运行时会报错，或界面取不到数据，我 review 也会提出来，但现在应该都没有。

2024-11-19 10:34 UTC, TechQuery requested changes

2024-11-19 10:34 UTC, TechQuery commented on pages/issue/index.tsx
> +    return { props: { list } as IssuePageProps };
```suggestion
    const list = await new IssueModel().getList(query);

    return { props: JSON.parse(JSON.stringify({ list }) as IssuePageProps });
```

2024-11-19 10:34 UTC, TechQuery commented on pages/issue/index.tsx
> +    </header>
把飞书多维表格中对应的表单链接也加上

2024-11-19 13:38 UTC, luojiyin1987 commented on models/Governance/Issue.ts
> +  }
已经删除

2024-11-19 13:47 UTC, luojiyin1987 commented on pages/issue/index.tsx
> +    return { props: { list } as IssuePageProps };
不应该是  
```Typescript
return { props: JSON.parse(JSON.stringify({ list })) as IssuePageProps };  ? 
```

2024-11-19 14:20 UTC, luojiyin1987 commented
报错 ，我定位不了
```bash
in aggregate the browser will display markup and comments as text in the title and hydration will likely fail and fall back to client rendering
    at title
    at head
    at Head (/home/luo/nodeWork/kaiyuanshe.github.io/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/pages/_document.js:317:1)
    at html
    at Html (/home/luo/nodeWork/kaiyuanshe.github.io/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/pages/_document.js:779:131)
    at Document
```

浏览器页面报错
```bash
Error: Objects are not valid as a React child (found: object with keys {text, type}). If you meant to render a collection of children, use an array instead.
```

2024-11-19 16:16 UTC, TechQuery commented on pages/issue/index.tsx
> +    return { props: { list } as IssuePageProps };
> 不应该是  
> ```Typescript
> return { props: JSON.parse(JSON.stringify({ list })) as IssuePageProps };  ? 
> ```

不好意思，手机上打错了，已经改了。

2024-11-19 16:20 UTC, TechQuery commented
> 浏览器页面报错
> ```text
> Error: Objects are not valid as a React child (found: object with keys {text, type}). If you meant to render a collection of children, use an array instead.
> ```

它说：你直接把一个 `{text, type}` 结构的对象让它渲染没法搞。

你需要取 `text` 字段值给 React。

2024-11-20 02:59 UTC, luojiyin1987 commented
> > 浏览器页面报错
> > ```
> > Error: Objects are not valid as a React child (found: object with keys {text, type}). If you meant to render a collection of children, use an array instead.
> > ```
> 
> 它说：你直接把一个 `{text, type}` 结构的对象让它渲染没法搞。
> 
> 你需要取 `text` 字段值给 React。


通过排除法 ，确定问题在  ScrollList 部分代码。  还在找具体的原因。

2024-11-20 05:03 UTC, TechQuery commented
> 通过排除法 ，确定问题在  ScrollList 部分代码。  还在找具体的原因。

虽然最终报错是在里面，但这明显就是有一个飞书文本字段的数据没处理成纯文本。

2024-11-20 07:25 UTC, luojiyin1987 commented
通过  title: JSON.stringify(title), 得到值为 
```json
[{"text":"[Proposal] 成立开源项目孵化辅导咨询委员会","type":"text"}]
```
我写的 model 中的 normalize 函数 有问题？   @TechQuery

2024-11-20 08:31 UTC, luojiyin1987 commented
数据类型报错已经解决，  
```typescript
createdBy: (createdBy as TableCellUser)?.en_name || '',
```
但是报类型错误 ，
```bash
Conversion of type 'string | number | boolean | TableCellLocation | TableCellLink | (string | TableCellLink | TableCellText | ... 6 more ... | TableCellRelation)[] | null' to type 'TableCellUser' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type '(string | TableCellLink | TableCellText | TableCellMedia | TableCellAttachment | TableCellUser | TableCellGroup | TableCellUserMetion | TableCellDocumentMetion | TableCellRelation)[]' is missing the following properties from type 'TableCellUser': id, name, en_name, emailts(2352)
```
@TechQuery

2024-11-20 15:09 UTC, TechQuery commented
> ```typescript
> createdBy: (createdBy as TableCellUser)?.en_name || '',
> ```
> 但是报类型错误 ，
> ```bash
> Conversion of type 'string | number | boolean | TableCellLocation | TableCellLink | (string | TableCellLink | TableCellText | ... 6 more ... | TableCellRelation)[] | null' to type 'TableCellUser' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
>   Type '(string | TableCellLink | TableCellText | TableCellMedia | TableCellAttachment | TableCellUser | TableCellGroup | TableCellUserMetion | TableCellDocumentMetion | TableCellRelation)[]' is missing the following properties from type 'TableCellUser': id, name, en_name, emailts(2352)
> ```

用 `TableCellUserMetion` 类型，它才是在各类文档中引用一个用户的数据结构。

2024-11-20 16:17 UTC, TechQuery commented
> 有  name 字段  没 en_name 字段     .我要去维护 type 文件 ？   @TechQuery 

每种数据结构有哪些查询出来的字段都是我在类型层面梳理过的，没有就是没有，有啥用啥。

2024-11-21 03:12 UTC, luojiyin1987 commented
现在还是报  `Property 'en_name' does not exist on type 'TableCellUserMetion[]'.ts(2339)`       

```typescript
createdBy: (createdBy as TableCellUserMetion[])?.en_name || '',
```

2024-11-21 11:17 UTC, TechQuery commented
> 现在还是报  `Property 'en_name' does not exist on type 'TableCellUserMetion[]'.ts(2339)`       
> 
> ```typescript
> createdBy: (createdBy as TableCellUserMetion[])?.en_name || '',
> ```

对呀，数组上怎么可能直接有属性嘛，这个字段只可能有一个人，默认取第一项就行了。

2024-11-21 12:44 UTC, luojiyin1987 commented
> > 现在还是报  `Property 'en_name' does not exist on type 'TableCellUserMetion[]'.ts(2339)`
> > ```ts
> > createdBy: (createdBy as TableCellUserMetion[])?.en_name || '',
> > ```
> 
> 对呀，数组上怎么可能直接有属性嘛，这个字段只可能有一个人，默认取第一项就行了。

```typescript
createdBy: (createdBy as TableCellUserMetion)?.en_name  || '',
```
这样 ？

2024-11-21 16:11 UTC, TechQuery requested changes

2024-11-21 16:11 UTC, TechQuery commented on models/Governance/Issue.ts
> +      department,
```suggestion
      createdBy,
      department,
```

2024-11-21 16:11 UTC, TechQuery commented on models/Governance/Issue.ts
> +      createdBy: (createdBy as TableCellUser)?.name || '',
已修复：https://github.com/idea2app/MobX-Lark/releases/tag/v2.0.0

2024-11-21 16:28 UTC, luojiyin1987 commented on models/Governance/Issue.ts
> +      createdBy: (createdBy as TableCellUser)?.name || '',
已经在  package.json 更新 mobx-lark 版本

2024-11-21 17:39 UTC, TechQuery commented on models/Governance/Issue.ts
> +      createdBy: (createdBy as TableCellUser)?.name || '',
> 已经在 package.json 更新 mobx-lark 版本

但没执行 `pnpm i`，导致 CI/CD 流水线挂掉：
![image](https://github.com/user-attachments/assets/2730ec47-9c80-4cd5-895e-2b19abc90079)

2024-11-22 12:42 UTC, TechQuery approved these changes

2024-11-22 12:43 UTC, merged