意见箱  提案库显示更多信息
kaiyuanshe/kaiyuanshe.github.io pull request #371
Opened 2024-11-25 03:27 UTC by luojiyin1987

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2024-11-26 10:02 UTC, TechQuery requested changes
多个地方的同类问题请一起改。

2024-11-26 10:02 UTC, TechQuery commented on components/Proposal/Card.tsx
> +    <Card.Footer className="d-flex flex-wrap justify-content-between align-items-center"></Card.Footer>
此处可以显示时间戳之类的单项内容。

2024-11-26 10:02 UTC, TechQuery commented on translation/en-US.ts
>    // Proposal pages
```suggestion
  detail: 'Detail',

   // Proposal pages
```

2024-11-26 15:30 UTC, luojiyin1987 commented on components/Issue/Card.tsx
> +        {detail && marked(detail as string)}
是 `dangerouslySetInnerHTML`  吧 ？

2024-11-26 15:42 UTC, TechQuery commented on components/Issue/Card.tsx
> +        {detail && marked(detail as string)}
> 是 `dangerouslySetInnerHTML`  吧 ？ 

嗯，太长记不住。

2024-11-27 09:37 UTC, TechQuery requested changes

2024-11-27 09:37 UTC, TechQuery commented on components/Issue/Card.tsx
> +      </Row>
```suggestion
      {textJoin(t('related'), t('department'))}: 
      <a className="text-decoration-none" href={`/department/${department}`}>
          {department as string}
      </a>
```

2024-11-27 09:37 UTC, TechQuery commented on components/Issue/Card.tsx
> +              <li key={index} className="mt-2">
```suggestion
            (meetings[0] as TableCellRelation).text_arr.map((text, index) => (
              <li key={text} className="mt-2">
```

2024-11-27 14:42 UTC, TechQuery approved these changes

2024-11-27 14:48 UTC, merged