[add]Members
kaiyuanshe/kaiyuanshe.github.io pull request #77
Opened 2022-11-03 15:50 UTC by Five-great

Checklist（清单）:

- [X] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #70

2022-11-03 17:38 UTC, TechQuery requested changes

2022-11-03 17:38 UTC, TechQuery commented on components/Members/MembersList.tsx
> +                    href: '' + new URL('' + GitHubID, 'https://github.com'),
```suggestion
                    href: `https://github.com/${GitHubID}`,
```

2022-11-03 17:38 UTC, TechQuery commented on components/Members/MembersList.tsx
> +                <i className="d-block fst-normal overflow-hidden">
```suggestion
                className={`d-inline-block position-relative text-truncate ${styles.btn_ta}`}
                data-text={nickname || name || '成员X'}
              >
                <i className="d-inline-block fst-normal overflow-hidden">
```
尽量不要改变标签的 `display` 的对外语义，`inline-block` 可以提供对内的宽高设置

2022-11-03 17:38 UTC, TechQuery commented on components/Members/MembersTabs.tsx
> +}>;
```suggestion
type TabsData = Record<string, {
  list: Member[];
}>;

export interface MembersTabsProps {
  tabs?: TabsData;
```
只有组件的参数对象才称为 Props，内层数据结构都与 React 无关（下同）

2022-11-03 17:38 UTC, TechQuery commented on components/Members/MembersTabs.tsx
> +            <MembersList list={tabs[tabKey]?.list} />
```suggestion
        Object.entries(tabs).map(([key, { list }]) => (
          <Tab
            key={key}
            eventKey={key}
            tabClassName="p-2"
            title={key + '(' + list.length + ')'}
          >
            <MembersList list={list} />
```
（下同）

2022-11-03 17:38 UTC, TechQuery commented on styles/globals.less
> +  }
```suggestion
  @media only screen and (min-width: 768px) {
    min-height: calc(100vh - 11.4rem);
  }
```

2022-11-03 17:38 UTC, TechQuery commented on styles/globals.less
> +}
放在具体组件的模块 CSS 中

2022-11-03 17:38 UTC, TechQuery commented on styles/Members.module.less
> +  }
```suggestion
  &::-webkit-scrollbar-thumb {
    border-radius: 5px;
    background: #dddddd;
    &:hover {
      border-radius: 5px;
      box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
      background: #a1a1a1;
    }
  }
```
（下同）

2022-11-03 17:38 UTC, TechQuery commented on styles/Members.module.less
> +  }
```suggestion
  img.error {
    border: 2px solid red;
  }
```
尽量用 CSS class（上同）

2022-11-03 17:38 UTC, TechQuery commented on pages/members/index.tsx
> +    };
```suggestion
  @observable
  membersGroup = {} as MembersGroup;

  @observable
  otherMembersList: Member[] = [];
```
直接用 MobX 更简洁：https://github.com/mobxjs/mobx/blob/mobx4and5/docs/refguide/observer-component.md#local-observable-state-in-class-based-components

2022-11-03 17:38 UTC, TechQuery commented on pages/members/index.tsx
> +    });
https://web-cell.dev/web-utility/functions/groupBy.html
用这个工具函数预处理会简单很多

2022-11-04 01:07 UTC, Five-great commented on components/MainNav.tsx
> +              src={logo || '/kaiyuanshe.png'}
其实我想换成本地的 GitHub 有点慢 我要不开梯子 我看来一下是个环境变量 可以换 云存储 就直接logo变量吧

2022-11-04 01:18 UTC, Five-great commented on components/Members/MembersTitle.tsx
> +  return (
我参考其他页面的 其他页面我也改一下吧

2022-11-04 01:24 UTC, Five-great commented on styles/Members.module.less
> +  }
这个是我之前测试的 我删掉

2022-11-04 01:45 UTC, Five-great commented on utils/layzload.ts
> +}
我知道这个 目前还在实验阶段 ，目前原生还不支持 默认图，想着要是网路状态不佳 先显示默认的 开源社的图
![92c3a7a2e9203d256bc2926fabe7311](https://user-images.githubusercontent.com/43601963/199867269-43f4ba16-29c8-4d1a-8df7-41effbf727e6.jpg)
有一个占位符的意思 个人喜好 个人喜好 😁
![45a3cf071659b24082d3c4e07d26367](https://user-images.githubusercontent.com/43601963/199867289-ba925734-1102-426f-aa81-f9e3daba0043.jpg)

2022-11-04 05:29 UTC, Five-great commented on pages/members/index.tsx
> +    });
groupBy我看了 但是目前不太适合 成员的数据的😂，成员的数据和结构有点问题（分组暂时是需要对3个字段的分类做处理），做了一些处理，groupBy 适合单字段分类解决方案，还有就是 用groupBy函数  顺序没法固定 比如 理事会 顾问委员会 法律咨询委员会 顺序固定，当然也可以处理一下，还有就是无法获取 未分组成员，还有一点就是 总数据会遍历至少3次 自己实现 遍历一遍，当然性能节省 也不太多 数据量不大

2022-11-04 15:34 UTC, TechQuery requested changes

2022-11-04 15:34 UTC, TechQuery commented on components/Members/MembersList.tsx
> +      } ${styles.memberRow}`}
动态 class 拼接用 https://www.npmjs.com/package/classnames

2022-11-04 15:34 UTC, TechQuery commented on components/Members/MembersTabs.tsx
> +>;
```suggestion
type TabData = Record<string, { list: Member[]; }>;

type TabsData = Record<string, Record<string, TabData>>;

```
（下同）

2022-11-04 15:34 UTC, TechQuery commented on components/Members/MembersTabs.tsx
> +            <MembersList list={list as unknown as Member[]} />
此处类型是确定的吧？不需要断言吧？

2022-11-04 15:34 UTC, TechQuery commented on pages/members/index.tsx
> +  );
```suggestion
) => {
  for (const key of groupKeys)
    ((groupMap[key] ||= { list: [] }).list as Member[]).push(groupItem);
```
参数类型声明 `groupKeys` 一定存在，空数组会自动跳过迭代，故在最前的回调函数就可以放到外面执行。

2022-11-04 15:34 UTC, TechQuery commented on pages/members/index.tsx
>    async componentDidMount() {
```suggestion
  otherMembersList: Member[] = [];

  async componentDidMount() {
```

2022-11-04 15:34 UTC, TechQuery commented on pages/members/index.tsx
>      list.forEach((member: Member) => {
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

2022-11-04 15:34 UTC, TechQuery commented on pages/members/index.tsx
> +    membersGroup[projectKey].list = [...new Set(membersGroup[projectKey].list)];
https://github.com/tc39/proposal-array-unique

2022-11-04 15:34 UTC, TechQuery commented on pages/members/index.tsx
> +                ></MembersList>
```suggestion
                />
```

2022-11-04 15:34 UTC, TechQuery commented on styles/Members.module.less
> +  .btn_tamaya::after {
建议写成 LESS 嵌套语法，代码更简洁：
```less
.class {
    &::after {
    }
}
```

2022-11-04 15:38 UTC, TechQuery commented on pages/members/index.tsx
> +    });
你这不是明明也遍历了 3 次吗？未分组成员在处理回调时用空字符串等特定 key 来收集即可

2022-11-04 15:40 UTC, TechQuery commented on styles/globals.less
> +}
每个页面都引用组件的 JSX，模块样式就跟着组件实例走，都会打包，但也不会重复处理。

2022-11-05 01:44 UTC, Five-great commented on pages/members/index.tsx
> +    });
![image](https://user-images.githubusercontent.com/43601963/200094460-c7f91ba7-991c-4711-a320-a38437cadc79.png)

![image](https://user-images.githubusercontent.com/43601963/200094662-30b9621c-de31-404a-82cd-5ed42076335f.png)

![image](https://user-images.githubusercontent.com/43601963/200094886-3be38ce6-1d2e-4610-99e5-204d2546c333.png)
因为数据 分类要从3个字段 来 目前数据结构还有点不规范  项目委员会 我是将 所有项目的人代码逻辑 加进去的
![image](https://user-images.githubusercontent.com/43601963/200095141-2e2ee354-d286-4bc0-9907-a6c9d843da42.png)
未分组成员 得 organization department project 3个字段同时没有值才行😂 工具函数groupBy 貌似支持一个字段 分组
我考虑到 所有分组 直接排着显示有点过长  工作组增加数量 暂时算是有限的 现在基本算完整， 具体项目组 后续增加 就所不准，所以我把项目组 挂再 项目委员会里面的 通过Tabs展示 项目组成员 也会自动进入 项目委员会里面 可能我理解不对，也可以不加 Tabs 全部成员哪也可以变成 委员会 项目组人不添加到委员会里面
![image](https://user-images.githubusercontent.com/43601963/200095411-b7050ffd-2524-4b22-8bd7-fc62c12db3bc.png)

2022-11-05 01:47 UTC, Five-great commented on components/Members/MembersTabs.tsx
> +            <MembersList list={list as unknown as Member[]} />
这个编辑器提示 我也觉得不用 是确定的 它要报红 提示我改 是😂 这个锅 提示插件给我背锅

2022-11-05 01:49 UTC, Five-great commented on pages/members/index.tsx
> +  );
好的 我放到最外面 也行 groupKeys 根据目前数据不规范 或者未分组撒的可能没有从😂

2022-11-05 01:55 UTC, Five-great commented on pages/members/index.tsx
> +                ></MembersList>
好像是 格式化软件的问题 我注意下

2022-11-05 02:14 UTC, Five-great commented on pages/members/index.tsx
> +    membersGroup[projectKey].list = [...new Set(membersGroup[projectKey].list)];
这个是提案么 还是已经支持 不知道咋用 是需要引入或者配置么 不知道其他地方有去重没 很多地方有 去重需求 原型链上直接一劳永逸 还是可以，语义化也好点的😂

2022-11-05 02:23 UTC, Five-great commented on styles/globals.less
> +}
嗯嗯 这个知道 我不是说会重复的意思， 只是感觉每个都有算公共组件 单独写弄出来编译多加载一个文件， 当然确实模块化的化还是分开一下 毕竟他mainNav 都分开了 在理 😁😁

2022-11-05 02:31 UTC, Five-great commented on utils/layzload.ts
> +}
恕我愚钝 的😂 这里 没懂 是说的 懒加载  写到里面么 我开始方案 最后统一处理 ，不用调用那么多次 lazy 的函数 我开发模式看放到里面 会重复多次 不知道生产模式会怎样，我是想着节省那部分性能有点像 监听多个li  和 在ul 代理监听的区别的😂

2022-11-05 07:36 UTC, TechQuery commented on pages/members/index.tsx
> +    membersGroup[projectKey].list = [...new Set(membersGroup[projectKey].list)];
```shell
pnpm i array-unique-proposal
```

```ts
import 'array-unique-proposal';

[1, 1].uniqueBy();
```

2022-11-05 07:39 UTC, TechQuery commented on utils/layzload.ts
> +}
如果代码行文更语义化，利于维护，一点点性能牺牲是值得的，但我没觉得哪儿有明显的性能损失。

2022-11-08 04:33 UTC, Five-great commented on utils/layzload.ts
> +}
```ts
import { PureComponent } from 'react';
import { Image, ImageProps } from 'react-bootstrap';

export interface LazyImageProps extends ImageProps {
  preLazySrc?: string; //👈 懒加载前的占位图src
  errorSrc?: string; //👈 懒加载图片加载失败替换图src
} 

export class LazyImage extends PureComponent<LazyImageProps> {
  LazyImageRef: HTMLImageElement | undefined;

  componentDidMount() {
    const lazyImage = this.LazyImageRef as Element;
    const observer = new IntersectionObserver((entries: any) => {
      entries[0].isIntersecting &&
        (lazyImage.setAttribute('src', '' + this.props.src),
        observer.unobserve(lazyImage));
    });
    observer.observe(lazyImage);
  }

  render() {
    const {
      preLazySrc = '/kaiyuanshe.png',
      errorSrc = '/kaiyuanshe.png',
      alt,
    } = this.props;
    return (
      <Image
        ref={(element: HTMLImageElement) => (this.LazyImageRef = element)}
        {...this.props}
        src={preLazySrc}
        alt={alt}
        onError={({ currentTarget }) => (currentTarget.src = errorSrc)}
      />
    );
  }
}
```

2022-11-08 15:04 UTC, TechQuery requested changes

2022-11-08 15:04 UTC, TechQuery commented on components/LazyImage.tsx
> +        ref={(element: HTMLImageElement) => (this.LazyImageRef = element)}
```suggestion
  watch(image: HTMLImageElement | null) {
    if (!image) return;

    const observer = new IntersectionObserver(([{ isIntersecting }]) => {
      if (!isIntersecting) return;

      image.src = this.props.src;
      
      observer.unobserve(image);
    });
    observer.observe(image);
  }

  render() {
    const {
      preLazySrc = '/kaiyuanshe.png',
      errorSrc = '/kaiyuanshe.png',
      alt,
    } = this.props;

    return (
      <Image
        ref={this.watch}
```

2022-11-09 01:13 UTC, Five-great commented on .gitignore
> +.env.development
ok  忘删除了这

2022-11-09 12:04 UTC, TechQuery requested changes

2022-11-09 12:04 UTC, TechQuery commented on components/LazyImage.tsx
> +        ref={this.watch.bind(this)}
```suggestion
  watch = (image: HTMLImageElement | null) => {
    if (!image) return;

    const observer = new IntersectionObserver(([{ isIntersecting }]) => {
      if (!isIntersecting) return;

      image.src = this.props.src as string;

      observer.unobserve(image);
    });
    observer.observe(image);
  }

  render() {
    const {
      preLazySrc = '/kaiyuanshe.png',
      errorSrc = '/kaiyuanshe.png',
      alt,
    } = this.props;

    return (
      <Image
        ref={this.watch}
```

2022-11-09 12:04 UTC, TechQuery commented on pages/members/index.tsx
> +          Object.keys(membersGroup).map((groupName: string) => (
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

2022-11-09 13:02 UTC, TechQuery commented on components/LazyImage.tsx
> +        ref={this.watch.bind(this)}
这是 ECMAScript 2022 正式标准，也是很多年的提案了，主要是简化实例成员的创建。

2022-11-09 13:04 UTC, TechQuery approved these changes

2022-11-09 13:05 UTC, merged

2022-11-09 14:18 UTC, Five-great commented on components/LazyImage.tsx
> +        ref={this.watch.bind(this)}
提案 撒的 我关注得比较少 可以说完全没有咋个关注是😂😂😂 后面得多了解一下

2022-11-09 15:20 UTC, TechQuery commented on components/LazyImage.tsx
> +        ref={this.watch.bind(this)}
https://jscig.github.io/

2022-11-09 15:26 UTC, TechQuery commented on utils/layzload.ts
> +}
全局共享一个 Observer 还得考虑怎么传递每个图片的 `src`，而且**观察者系列 API** 就是为了解决传统事件监听多了会卡的问题，一个萝卜一个坑比较清晰，浏览器内部应该做了性能优化：
https://developer.mozilla.org/zh-CN/docs/Web/API/Intersection_Observer_API