活动列表页
kaiyuanshe/kaiyuanshe.github.io pull request #81
Opened 2022-11-14 14:21 UTC by Guanngxu

Checklist（清单）:

- [ ] Labels
- [ ] Assignees
- [ ] Reviewers

Closes #XXXXX

2022-11-16 22:08 UTC, TechQuery requested changes
参照 #84 支持搜索活动

2022-11-16 22:08 UTC, TechQuery commented on models/Activity.ts
> +  });
在此处理文本字段，页面代码更简单，参考：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/e574376e8fd454abee65821e816a6b8054150cb4/models/Group.ts#L29-L38

2022-11-16 22:08 UTC, TechQuery commented on pages/activity/index.tsx
> +        </Row>
参考最新代码，简化列表实现：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/e574376e8fd454abee65821e816a6b8054150cb4/components/Article/List.tsx#L10-L29

2022-11-16 22:08 UTC, TechQuery commented on pages/activity/index.tsx
> +}
参考最新代码，简化页面实现：
https://github.com/kaiyuanshe/kaiyuanshe.github.io/blob/e574376e8fd454abee65821e816a6b8054150cb4/pages/article/index.tsx#L8-L26

2022-11-22 15:34 UTC, Guanngxu commented
> 参照 #84 支持搜索活动

已支持活动搜索

2022-11-22 17:03 UTC, TechQuery approved these changes

2022-11-22 17:04 UTC, merged