[refactor] Members Page SSR by Five
kaiyuanshe/kaiyuanshe.github.io pull request #85
Opened 2022-11-18 06:15 UTC by Five-great

Checklist（清单）:

- [x] Labels
- [x] Assignees
- [x] Reviewers

Closes #82

2022-11-20 12:11 UTC, TechQuery requested changes

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +const groupFn = function <T>(
```suggestion
function groupFn<T>(
```
（下同）

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +    hasGroup = false;
```suggestion

  for (const item of items) {
    let hasGroup = false;
```

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +        (groupAllMap[byKey] = groupAllMap[byKey] || { count: 0, groupMap: {} })
```suggestion
        (groupAllMap[byKey] ||= { count: 0, groupMap: {} })
```

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +      if (item[byKey]) groupAllMap[byKey].count++, (hasGroup = true);
```suggestion
      if (item[byKey]) {
        groupAllMap[byKey].count++;
        hasGroup = true;
      }
```

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +    const groupMap: any = Object.assign(
不要有 `any`

2022-11-20 12:11 UTC, TechQuery commented on models/Member.ts
> +      otherGroupList,
```suggestion

    return {
      groupMap,
      otherGroupList: groupData.unGrouped,
```

2022-11-20 12:11 UTC, TechQuery commented on pages/members/index.tsx
> +    props: { membersStaticData: JSON.parse(JSON.stringify(await membersStore.getStatic())) }, // will be passed to the page component as props
```suggestion
  const data = await membersStore.getStatic();

  return {
    props: { membersStaticData: JSON.parse(JSON.stringify(data)) }, // will be passed to the page component as props
```

2022-11-20 12:11 UTC, TechQuery commented on pages/members/index.tsx
> +      {downloading > 0 && <Loading />}
```suggestion
  const { groupMap, otherGroupList } = membersStaticData;

  return (
    <Container className="my-4">
```
现在是服务端渲染，是没有客户端加载状态的。

2022-11-21 01:39 UTC, Five-great commented on pages/members/index.tsx
> +      {downloading > 0 && <Loading />}
疏忽了 搞忘删了

2022-11-21 14:41 UTC, TechQuery commented on models/Member.ts
> +    ((groupMap[key] = groupMap[key] || { list: [] }).list as T[]).push(
```suggestion
    ((groupMap[key] ||= { list: [] }).list as T[]).push(
```

2022-11-21 14:42 UTC, TechQuery commented on pages/members/index.tsx
> +  return (
```suggestion
  const { groupMap, otherGroupList } = membersStaticData;

  return (
```

2022-11-21 14:46 UTC, merged